export interface IqQuestion {
  id: number;
  domain: 'matrix' | 'numerical' | 'verbal' | 'spatial' | 'logic';
  difficulty: number; // 1 to 5
  questionAr: string;
  questionEn: string;
  type: 'text' | 'visual_matrix' | 'sequence';
  matrixData?: {
    grid: (string | null)[];
    options: string[];
  };
  optionsAr: string[];
  optionsEn: string[];
  correctIndex: number;
  explanationAr: string;
  explanationEn: string;
}

export const IQ_QUESTIONS: IqQuestion[] = [
  {
    id: 1,
    domain: 'matrix',
    difficulty: 1,
    questionAr: 'أكمل المصفوفة البصرية الاستقرائية التالية باختيار الشكل الصحيح:',
    questionEn: 'Complete the visual progressive matrix by choosing the correct figure:',
    type: 'visual_matrix',
    matrixData: {
      grid: ['▲', '■', '●', '▲▲', '■■', '●●', '▲▲▲', '■■■', null],
      options: ['●●●', '◆◆◆', '★★★★★', '▲▲▲▲'],
    },
    optionsAr: ['ثلاث دوائر (●●●)', 'ثلاث معينانات (◆◆◆)', 'خمس نجوم (★★★★★)', 'أربع مثلثات (▲▲▲▲)'],
    optionsEn: ['Three circles (●●●)', 'Three diamonds (◆◆◆)', 'Five stars (★★★★★)', 'Four triangles (▲▲▲▲)'],
    correctIndex: 0,
    explanationAr: 'النمط يتصاعد عمودياً وأفقياً بزيادة عدد الأشكال بمقدار واحد لكل صف: مثلث، مربع، ثم دائرة بعدد يتطابق مع الصف الثالث.',
    explanationEn: 'The pattern increases by one shape per column and row: triangle, square, then circle matching the row count.',
  },
  {
    id: 2,
    domain: 'numerical',
    difficulty: 2,
    questionAr: 'ما هو الرقم المفقود في السلسلة الحسابية التالية: 2, 6, 12, 20, 30, ?',
    questionEn: 'What is the missing number in the numerical series: 2, 6, 12, 20, 30, ?',
    type: 'sequence',
    optionsAr: ['38', '42', '46', '50'],
    optionsEn: ['38', '42', '46', '50'],
    correctIndex: 1,
    explanationAr: 'الفرق بين الأعداد يزيد بمقدار 2 في كل خطوة (+4, +6, +8, +10, +12). إذن 30 + 12 = 42.',
    explanationEn: 'The differences between consecutive numbers increase by 2 (+4, +6, +8, +10, +12). Thus 30 + 12 = 42.',
  },
  {
    id: 3,
    domain: 'verbal',
    difficulty: 2,
    questionAr: 'إذا كانت كلمة "سريع" تعكس "بطيء"، فما هو عكس كلمة "دقيق" أو "محكم"؟',
    questionEn: 'If "fast" is to "slow", what is the antonym of "precise" or "rigorous"?',
    type: 'text',
    optionsAr: ['عشوائي / مهمل', 'سريع', 'ذكي', 'قوي'],
    optionsEn: ['Random / Careless', 'Fast', 'Smart', 'Strong'],
    correctIndex: 0,
    explanationAr: 'العلاقة هي التضاد المباشر في المعنى الدلالي بين الدقة والضبط في مقابل العشوائية والإهمال.',
    explanationEn: 'The relationship is direct antonymous meaning between precision and randomness/carelessness.',
  },
  {
    id: 4,
    domain: 'spatial',
    difficulty: 3,
    questionAr: 'إذا تم تدوير مكعب مرسوم على أوجهه أشكال (دائرة، مربع، مثلث، نجمة، معين، سهم) بزاوية 90 درجة لليمين ثم 180 لأعلى، أي علاقة مكانية تبقى ثابتة؟',
    questionEn: 'If a cube with symbols on its faces is rotated 90 deg right then 180 deg up, which spatial relationship remains constant?',
    type: 'text',
    optionsAr: ['التقابل النسبي بين الأوجه المتقابلة', 'موقع الأشكال على الشاشة', 'اتجاه الجاذبية للأعلى', 'لون خلفية المكعب'],
    optionsEn: ['Relative adjacency of opposite faces', 'Screen coordinates of shapes', 'Gravity vector direction', 'Background color'],
    correctIndex: 0,
    explanationAr: 'في الهندسة الفراغية، التلاصق والتقابل بين أسطح المكعب يظل ثابتاً بغض النظر عن زاوية الدوران.',
    explanationEn: 'In spatial geometry, topological adjacency of cube faces remains invariant under rotation.',
  },
  {
    id: 5,
    domain: 'logic',
    difficulty: 3,
    questionAr: 'جميع المهندسين يقرأون الكتب التقنية. بعض الأشخاص الذين يقرأون الكتب التقنية هم مبدعون. هل بالضرورة بعض المهندسين مبدعون؟',
    questionEn: 'All engineers read technical books. Some people who read technical books are creative. Is it necessarily true that some engineers are creative?',
    type: 'text',
    optionsAr: ['غير مؤكد منطقياً بشكل قاطع', 'نعم بالتأكيد', 'لا مستحيل قطعا', 'البيانات ناقصة تماماً'],
    optionsEn: ['Not logically certain (contingent)', 'Yes, absolutely', 'No, impossible', 'Data is completely insufficient'],
    correctIndex: 0,
    explanationAr: 'من الناحية المنطقية الرياضية، تداخل مجموعتين لا يضمن التقاطع الحتمي مع المجموعة الفرعية الأولى دون دليل إضافي.',
    explanationEn: 'Logically, subset intersection does not strictly guarantee overlap with the specific subgroup without extra premises.',
  },
  {
    id: 6,
    domain: 'matrix',
    difficulty: 4,
    questionAr: 'أي من الأشكال التالية يكمل النمط الهندسي للدوران المتسارع: (⟳ 90°، ⟳ 180°، ⟳ 270°، ?)',
    questionEn: 'Which figure completes the accelerating rotation pattern: (⟳ 90°, ⟳ 180°, ⟳ 270°, ?)',
    type: 'text',
    optionsAr: ['⟳ 360° (أو دورة كاملة 0°)', '⟳ 45°', '⟳ 90° عكسي', '⟳ 540°'],
    optionsEn: ['⟳ 360° (Complete cycle 0°)', '⟳ 45°', '⟳ 90° reverse', '⟳ 540°'],
    correctIndex: 0,
    explanationAr: 'الزيادة في الزاوية هي +90 درجة في كل خطوة (90، 180، 270، 360).',
    explanationEn: 'The angular increment is +90 degrees at each step (90, 180, 270, 360).',
  },
  {
    id: 7,
    domain: 'numerical',
    difficulty: 3,
    questionAr: 'ما هو العدد الذي إذا ضربته في 3 ثم أضفت إليه 12 ثم قسمته على 2 كان الناتج 21؟',
    questionEn: 'What number, when multiplied by 3, plus 12, divided by 2, equals 21?',
    type: 'sequence',
    optionsAr: ['10', '12', '14', '16'],
    optionsEn: ['10', '12', '14', '16'],
    correctIndex: 0,
    explanationAr: 'عكسياً: (21 × 2) = 42؛ (42 - 12) = 30؛ (30 ÷ 3) = 10.',
    explanationEn: 'Working backwards: (21 * 2) = 42; (42 - 12) = 30; (30 / 3) = 10.',
  },
  {
    id: 8,
    domain: 'spatial',
    difficulty: 4,
    questionAr: 'ورقة مربعة طويت مرتين ثم قُصت زواياها، كم عدد الثقوب الناتجة عند فردها بالكامل؟',
    questionEn: 'A square paper is folded twice and its corners are cut off. How many holes appear when unfolded?',
    type: 'text',
    optionsAr: ['4 ثقوب', '1 ثقب', '2 ثقوب', '8 ثقوب'],
    optionsEn: ['4 holes', '1 hole', '2 holes', '8 holes'],
    correctIndex: 0,
    explanationAr: 'الطي مرتين ينتج 4 طبقات متداخلة في الزاوية المقصوصة، وعند الفرد يظهر ثقب واحد في كل ركن بإجمالي 4 ثقوب.',
    explanationEn: 'Folding twice creates 4 overlapping layers at the corner; unfolding reveals 1 hole per quadrant = 4 holes.',
  },
  {
    id: 9,
    domain: 'verbal',
    difficulty: 3,
    questionAr: 'اختر الكلمة الشاذة أو غير المنتمية للمجموعة:',
    questionEn: 'Choose the odd word out:',
    type: 'text',
    optionsAr: ['الحديد', 'الألومنيوم', 'النحاس', 'الزجاج'],
    optionsEn: ['Iron', 'Aluminum', 'Copper', 'Glass'],
    correctIndex: 3,
    explanationAr: 'الحديد والألومنيوم والنحاس كلها معادن موصلة، بينما الزجاج مادة عازلة وليست معدناً.',
    explanationEn: 'Iron, aluminum, and copper are conductive metals, whereas glass is an insulator and non-metal.',
  },
  {
    id: 10,
    domain: 'matrix',
    difficulty: 5,
    questionAr: 'في مصفوفة الأشكال المتداخلة، إذا كان المربع يرمز لـ 4، والدائرة لـ 3، والمعين لـ 6، فما هي قيمة (مربع × معين - دائرة)؟',
    questionEn: 'In a symbolic matrix where Square = 4, Circle = 3, Diamond = 6, what is the value of (Square × Diamond - Circle)?',
    type: 'text',
    optionsAr: ['21', '18', '24', '15'],
    optionsEn: ['21', '18', '24', '15'],
    correctIndex: 0,
    explanationAr: '(4 × 6) = 24. ثم (24 - 3) = 21.',
    explanationEn: '(4 × 6) = 24. Then (24 - 3) = 21.',
  },
  {
    id: 11,
    domain: 'numerical',
    difficulty: 4,
    questionAr: 'ما هو العددان التاليان في متتالية فيبوناتشي: 1, 1, 2, 3, 5, 8, 13, ? , ?',
    questionEn: 'What are the next two numbers in the Fibonacci sequence: 1, 1, 2, 3, 5, 8, 13, ? , ?',
    type: 'sequence',
    optionsAr: ['21, 34', '19, 32', '24, 37', '22, 35'],
    optionsEn: ['21, 34', '19, 32', '24, 37', '22, 35'],
    correctIndex: 0,
    explanationAr: 'كل عدد هو مجموع العددين السابقين له: 8 + 13 = 21، ثم 13 + 21 = 34.',
    explanationEn: 'Each number is the sum of the two preceding ones: 8 + 13 = 21, then 13 + 21 = 34.',
  },
  {
    id: 12,
    domain: 'logic',
    difficulty: 5,
    questionAr: 'ثلاثة أشخاص (أ، ب، ج) أحدهم صادق دائماً والآخر كاذب دائماً والثالث متقلب (يصدق أحياناً ويكذب أحياناً). قال (أ): "أنا المتقلب". قال (ب): "أنا الصادق". قال (ج): "أنا الكاذب". من هو الصادق حقيقةً؟',
    questionEn: 'Three persons (A, B, C): one always tells truth, one always lies, one alternates. A says: "I am the alternator." B says: "I am the truthful one." C says: "I am the liar." Who is the truthful one?',
    type: 'text',
    optionsAr: ['ج (C)', 'أ (A)', 'ب (B)', 'لا يمكن التحديد'],
    optionsEn: ['C', 'A', 'B', 'Cannot be determined'],
    correctIndex: 0,
    explanationAr: 'بالتحليل المنطقي الصارم: إذا كان أ هو المتقلب، فهو صادق هنا بقوله. وإذا كان ج يقول "أنا الكاذب" وهو كاذب فعلياً فهذا مستحيل، وبالتالي التحليل الاستنتاجي يثبت أن الشخص (ج) هو صاحب الاستنتاج الصحيح الصادق.',
    explanationEn: 'By rigorous logical deduction of truth values and identities, C holds the consistent truth state under constraints.',
  },
];
