import { Glasses, Globe2, RotateCcw, ShieldCheck, Sun } from 'lucide-react';
import type { AppPreferences, Language } from '../../core/domain';
import { GLASS_OPTION, THEME_CATALOG } from '../../core/themeCatalog';

const c={ar:{title:'الإعدادات',sub:'تحكم في تجربة Adam بدون تغيير هويته.',appearance:'المظهر الأساسي',language:'اللغة',system:'النظام',light:'فاتح',dark:'داكن',glass:'Glass',reset:'إعادة تشغيل الإعداد الأولي',privacy:'الخصوصية أولاً',privacySub:'إعداداتك المحلية تبقى على جهازك ما لم تحتاجها ميزة.',arabic:'العربية',english:'English',glassOn:'تفعيل Glass',glassOff:'Glass متوقف',glassHint:'أضف اللمسة الزجاجية فوق الثيم الذي اخترته متى شئت.'},en:{title:'Settings',sub:'Tune your Adam experience without changing its identity.',appearance:'Base appearance',language:'Language',system:'System',light:'Light',dark:'Dark',glass:'Glass',reset:'Restart onboarding',privacy:'Privacy first',privacySub:'Your local preferences stay on-device unless a feature needs them.',arabic:'العربية',english:'English',glassOn:'Glass enabled',glassOff:'Glass off',glassHint:'Add the glass finish on top of any base theme whenever you want.'}};
const themeClass=(tone:string)=>`theme-preview theme-preview--${tone}`;

export function Settings({language,preferences,onChange}:{language:Language;preferences:AppPreferences;onChange:(p:Partial<AppPreferences>)=>void}){
 const t=c[language];
 return <section className="feature-page"><div className="feature-heading"><div><span className="eyebrow">ADAM / SETTINGS</span><h1>{t.title}</h1><p>{t.sub}</p></div></div><div className="settings-stack"><div className="settings-card"><div className="settings-title"><Sun size={19}/><div><strong>{t.appearance}</strong></div></div><div className="theme-grid">{THEME_CATALOG.map(theme=><button key={theme.id} className={preferences.theme===theme.id?'theme-option theme-option--rich selected':'theme-option theme-option--rich'} onClick={()=>onChange({theme:theme.id})} aria-pressed={preferences.theme===theme.id}><span className={themeClass(theme.tone)} aria-hidden="true"><i/><i/></span><span className="theme-copy"><strong>{theme.label[language]}</strong><small>{theme.description[language]}</small></span><span className="theme-check" aria-hidden="true">✓</span></button>)}</div></div><button className={preferences.glassEnabled?'glass-toggle glass-toggle--on':'glass-toggle'} onClick={()=>onChange({glassEnabled:!preferences.glassEnabled})} aria-pressed={preferences.glassEnabled}><span className="glass-toggle-icon"><Glasses size={18}/></span><span><strong>{preferences.glassEnabled?t.glassOn:t.glassOff}</strong><small>{t.glassHint}</small></span><span className="glass-switch" aria-hidden="true"><i/></span></button><div className="settings-card"><div className="settings-title"><Globe2 size={19}/><strong>{t.language}</strong></div><div className="theme-options"><button className={language==='ar'?'theme-option selected':'theme-option'} onClick={()=>onChange({language:'ar'})}>{t.arabic}</button><button className={language==='en'?'theme-option selected':'theme-option'} onClick={()=>onChange({language:'en'})}>{t.english}</button></div></div><div className="settings-card privacy-card"><div className="settings-title"><ShieldCheck size={19}/><div><strong>{t.privacy}</strong><p>{t.privacySub}</p></div></div></div><button className="danger-button" onClick={()=>{localStorage.clear();location.reload()}}><RotateCcw size={17}/>{t.reset}</button></div></section>}
