import { Moon, Sun, Monitor, Globe2, RotateCcw, ShieldCheck, Sparkles, Waves, Palette } from 'lucide-react';
import type { AppPreferences, Language, Theme } from '../../core/domain';

const c={ar:{title:'الإعدادات',sub:'تحكم كامل في تجربة Adam.',appearance:'المظهر',language:'اللغة',system:'النظام',light:'فاتح',dark:'داكن',glass:'Glass',glassDark:'Glass Dark',aurora:'Aurora',reset:'إعادة تشغيل الإعداد الأولي',privacy:'الخصوصية أولاً',privacySub:'إعداداتك المحلية لا تُرسل إلى الخادم إلا عند الحاجة.',arabic:'العربية',english:'English'},en:{title:'Settings',sub:'Full control over your Adam experience.',appearance:'Appearance',language:'Language',system:'System',light:'Light',dark:'Dark',glass:'Glass',glassDark:'Glass Dark',aurora:'Aurora',reset:'Restart onboarding',privacy:'Privacy first',privacySub:'Your local preferences stay on-device unless they are needed by a feature.',arabic:'العربية',english:'English'}};

export function Settings({language,preferences,onChange}:{language:Language;preferences:AppPreferences;onChange:(p:Partial<AppPreferences>)=>void}){
 const t=c[language];
 const themes:[Theme,string,typeof Sun][]=[['system',t.system,Monitor],['light',t.light,Sun],['dark',t.dark,Moon],['glass',t.glass,Waves],['glass-dark',t.glassDark,Sparkles],['aurora',t.aurora,Palette]];
 return <section className="feature-page"><div className="feature-heading"><div><span className="eyebrow">ADAM / SETTINGS</span><h1>{t.title}</h1><p>{t.sub}</p></div></div><div className="settings-stack"><div className="settings-card"><div className="settings-title"><Sun size={19}/><div><strong>{t.appearance}</strong></div></div><div className="theme-options">{themes.map(([id,label,Icon])=><button key={id} className={preferences.theme===id?'theme-option selected':'theme-option'} onClick={()=>onChange({theme:id})}><Icon size={17}/><span>{label}</span></button>)}</div></div><div className="settings-card"><div className="settings-title"><Globe2 size={19}/><strong>{t.language}</strong></div><div className="theme-options"><button className={language==='ar'?'theme-option selected':'theme-option'} onClick={()=>onChange({language:'ar'})}>{t.arabic}</button><button className={language==='en'?'theme-option selected':'theme-option'} onClick={()=>onChange({language:'en'})}>{t.english}</button></div></div><div className="settings-card privacy-card"><div className="settings-title"><ShieldCheck size={19}/><div><strong>{t.privacy}</strong><p>{t.privacySub}</p></div></div></div><button className="danger-button" onClick={()=>{localStorage.clear();location.reload()}}><RotateCcw size={17}/>{t.reset}</button></div></section>}
