import { ArrowLeft, ArrowRight, CalendarDays, Check, Cloud, Mail, Sparkles } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { AppPreferences, Language } from '../../core/domain';
import { initialOnboarding, nextStep, previousStep, type OnboardingState } from './onboardingModel';

export function Onboarding({ initial, onComplete }: { initial: AppPreferences; onComplete: (preferences: AppPreferences) => void }) {
  const [state, setState] = useState<OnboardingState>(() => initialOnboarding(initial));
  const isArabic = state.language === 'ar';
  const labels = useMemo(() => isArabic ? { welcome: 'مرحباً بك في Adam', name: 'كيف تحب أن أناديك؟', language: 'اختر لغتك', workspace: 'اربط مساحة عملك', ready: 'كل شيء جاهز', next: 'التالي', back: 'رجوع', finish: 'ابدأ مع Adam', optional: 'اختياري' } : { welcome: 'Welcome to Adam', name: 'What should I call you?', language: 'Choose your language', workspace: 'Connect your workspace', ready: 'You are ready', next: 'Continue', back: 'Back', finish: 'Start with Adam', optional: 'Optional' }, [isArabic]);
  const direction = isArabic ? 'rtl' : 'ltr';
  const stepIndex = ['welcome', 'language', 'workspace', 'ready'].indexOf(state.step);
  const advance = () => state.step === 'ready' ? onComplete({ agentName: state.agentName.trim() || 'Adam', language: state.language, theme: 'system', onboardingComplete: true }) : setState((s) => ({ ...s, step: nextStep(s.step) }));
  const toggle = (service: string) => setState((s) => ({ ...s, connected: s.connected.includes(service) ? s.connected.filter((x) => x !== service) : [...s.connected, service] }));
  return <div className="onboarding" dir={direction}><div className="onboarding-card"><div className="progress"><span style={{ width: `${((stepIndex + 1) / 4) * 100}%` }} /></div><div className="onboarding-content">
    <div className="onboarding-brand"><div className="hero-mark"><Sparkles size={23} /></div><span>ADAM</span></div>
    {state.step === 'welcome' && <div className="step-view"><span className="eyebrow">01 / 04</span><h1>{labels.welcome}</h1><p>{labels.name}</p><input autoFocus value={state.agentName} onChange={(e) => setState((s) => ({ ...s, agentName: e.target.value }))} maxLength={40} placeholder="Adam" onKeyDown={(e) => e.key === 'Enter' && advance()} /></div>}
    {state.step === 'language' && <div className="step-view"><span className="eyebrow">02 / 04</span><h1>{labels.language}</h1><div className="choice-list">{([['ar','العربية'],['en','English']] as const).map(([value,label]) => <button key={value} className={state.language === value ? 'choice choice--selected' : 'choice'} onClick={() => setState((s) => ({ ...s, language: value }))}><span>{label}</span>{state.language === value && <Check size={18} />}</button>)}</div></div>}
    {state.step === 'workspace' && <div className="step-view"><span className="eyebrow">03 / 04</span><h1>{labels.workspace}</h1><p>{labels.optional}</p><div className="choice-list"><button className={state.connected.includes('google') ? 'choice choice--selected' : 'choice'} onClick={() => toggle('google')}><span><Cloud size={18} /> Google Workspace</span>{state.connected.includes('google') && <Check size={18} />}</button><button className={state.connected.includes('calendar') ? 'choice choice--selected' : 'choice'} onClick={() => toggle('calendar')}><span><CalendarDays size={18} /> Calendar</span>{state.connected.includes('calendar') && <Check size={18} />}</button><button className={state.connected.includes('mail') ? 'choice choice--selected' : 'choice'} onClick={() => toggle('mail')}><span><Mail size={18} /> Email</span>{state.connected.includes('mail') && <Check size={18} />}</button></div></div>}
    {state.step === 'ready' && <div className="step-view ready-view"><div className="ready-check"><Check size={27} /></div><span className="eyebrow">04 / 04</span><h1>{labels.ready}</h1><p>{isArabic ? `${state.agentName}، Adam جاهز للعمل معك.` : `${state.agentName}, Adam is ready to work with you.`}</p></div>}
    <div className="onboarding-actions">{stepIndex > 0 ? <button className="secondary-button" onClick={() => setState((s) => ({ ...s, step: previousStep(s.step) }))}>{isArabic ? <ArrowRight size={17} /> : <ArrowLeft size={17} />}{labels.back}</button> : <span /> }<button className="primary-button" disabled={state.step === 'welcome' && state.agentName.trim().length < 2} onClick={advance}>{state.step === 'ready' ? labels.finish : labels.next}{isArabic ? <ArrowLeft size={17} /> : <ArrowRight size={17} />}</button></div>
  </div></div></div>;
}
