import type { Theme } from './domain';

export type ThemeCategory = 'all' | 'cinema' | 'cyber' | 'luxury' | 'nature' | 'minimal';

export type ThemeCatalogItem = {
  id: Theme;
  label: { ar: string; en: string };
  description: { ar: string; en: string };
  tone: Theme;
  badge?: { ar: string; en: string };
  category: ThemeCategory;
};

export const THEME_CATEGORIES = [
  { id: 'all' as const, label: { ar: 'الكل (QuickLiquid Glass)', en: 'All (QuickLiquid Glass)' }, icon: 'Sparkles' },
  { id: 'cinema' as const, label: { ar: '🎬 سينمائي ومسلسلات', en: '🎬 Cinema & Series' }, icon: 'Film' },
  { id: 'cyber' as const, label: { ar: '⚡ كود وسايبربانك', en: '⚡ Cyber & Dev' }, icon: 'Code' },
  { id: 'luxury' as const, label: { ar: '👑 فخامة ومخملي', en: '👑 Luxury & Velvet' }, icon: 'Crown' },
  { id: 'nature' as const, label: { ar: '🌿 طبيعة وريترو', en: '🌿 Nature & Retro' }, icon: 'Leaf' },
  { id: 'minimal' as const, label: { ar: '✨ مينيمال وزجاجي', en: '✨ Minimal & Glass' }, icon: 'Layout' },
] as const;

export const THEME_CATALOG: readonly ThemeCatalogItem[] = [
  {
    id: 'system',
    label: { ar: 'تلقائي النظام (QuickLiquid)', en: 'System Default (QuickLiquid)' },
    description: { ar: 'يتزامن تلقائيًا مع مظهر نظام جهازك مع زجاج انكساري ديناميكي.', en: 'Matches your OS appearance with dynamic refractive glass.' },
    tone: 'system',
    badge: { ar: 'QuickLiquid', en: 'QuickLiquid' },
    category: 'minimal',
  },
  {
    id: 'dark',
    label: { ar: 'نيون زمردي داكن (QuickLiquid)', en: 'Emerald Dark Liquid (Default)' },
    description: { ar: 'أسود فحمي مع لمسات زمردية أنيقة، انكسار زجاجي سائل وحواف مشعة.', en: 'Deep carbon black with vibrant emerald accents and QuickLiquid refraction.' },
    tone: 'dark',
    badge: { ar: 'Liquid Default', en: 'Liquid Default' },
    category: 'cyber',
  },
  {
    id: 'midnight',
    label: { ar: 'سواد منتصف الليل OLED (Liquid)', en: 'Midnight OLED Liquid' },
    description: { ar: 'سواد نقي وموفر للطاقة مريح جداً للعين مع أسطح زجاج سائل عميقة.', en: 'True pitch OLED black with refractive convex glass bezel optics.' },
    tone: 'midnight',
    badge: { ar: 'Liquid OLED', en: 'Liquid OLED' },
    category: 'minimal',
  },
  {
    id: 'light',
    label: { ar: 'أبيض ناصع ونقي (Liquid Glass)', en: 'Pure Crisp Light (Liquid)' },
    description: { ar: 'واجهة بيضاء مريحة وساطعة مع زجاج سائل كريستالي فائق النقاء.', en: 'Bright, high-contrast clarity with liquid glass dispersion.' },
    tone: 'light',
    badge: { ar: 'Liquid Light', en: 'Liquid Light' },
    category: 'minimal',
  },
  {
    id: 'glass',
    label: { ar: 'زجاجي كريستالي (QuickLiquid)', en: 'Crystal QuickLiquid Light' },
    description: { ar: 'شفافية زجاجية مضيئة مع انكسار بصري حقيقي وتشتت لوني سائل.', en: 'Frosted crystal light glass with optical QuickLiquid refraction.' },
    tone: 'glass',
    badge: { ar: 'Pure Glass', en: 'Pure Glass' },
    category: 'minimal',
  },
  {
    id: 'glass-dark',
    label: { ar: 'زجاج أوبسيديان داكن (QuickLiquid)', en: 'Obsidian QuickLiquid Dark' },
    description: { ar: 'زجاج بلوري معتم فائق العمق والشفافية مع محرك انكسار الأسطح السائلة.', en: 'Dark frosted glass powered by QuickLiquid optical refraction engine.' },
    tone: 'glass-dark',
    badge: { ar: 'Liquid Dark', en: 'Liquid Dark' },
    category: 'minimal',
  },
  {
    id: 'paper-clean',
    label: { ar: 'الورق النقي المينيمالي', en: 'Minimal Paper Clean' },
    description: { ar: 'بساطة الورق الطبيعي العاجي الخالي من أي تشتيت مع تباين طباعي فائق.', en: 'Clean warm ivory paper with ultra-crisp editorial typography and black ink.' },
    tone: 'paper-clean',
    badge: { ar: 'فاتح نقي', en: 'Editorial' },
    category: 'minimal',
  },
  {
    id: 'nord',
    label: { ar: 'نورد الجليدي الإسكندنافي', en: 'Arctic Nord Frost' },
    description: { ar: 'درجات برودة القطب الشمالي الرمادية والزرقاء الهادئة.', en: 'Calm arctic slate, icy cyan, and sub-zero aesthetic.' },
    tone: 'nord',
    badge: { ar: 'هادئ', en: 'Minimal' },
    category: 'minimal',
  },
  {
    id: 'stranger-things',
    label: { ar: 'سترينجر ثينقز (Stranger Things)', en: 'Stranger Things (Upside Down)' },
    description: { ar: 'أجواء هوكينز وعالم The Upside Down الغامض بأحمر نيون ثمانينات وسواد كوني عميق.', en: '80s Hawkins retro synth, glowing crimson neon, and ominous Upside Down atmosphere.' },
    tone: 'stranger-things',
    badge: { ar: 'سينمائي', en: 'Series' },
    category: 'cinema',
  },
  {
    id: 'peaky-blinders',
    label: { ar: 'بيكي بلايندرز (Peaky Blinders)', en: 'Peaky Blinders (Garrison)' },
    description: { ar: 'أجواء برمنغهام 1919 العتيقة بفحم دخاني داكن، نحاس تومي شيلبي، وجلد عتيق.', en: '1919 Birmingham grit, smoky vintage charcoal, weathered copper, and Shelby whiskey.' },
    tone: 'peaky-blinders',
    badge: { ar: 'سينمائي', en: 'Series' },
    category: 'cinema',
  },
  {
    id: 'breaking-bad',
    label: { ar: 'بريكينج باد (Breaking Bad)', en: 'Breaking Bad (Heisenberg Blue)' },
    description: { ar: 'صحراء نيو مكسيكو الكهرمانية مع زرقة كريستال والتر وايت وسواد ألبوكيرك.', en: 'New Mexico desert amber dunes, meth-crystal electric cyan, and Heisenberg noir.' },
    tone: 'breaking-bad',
    badge: { ar: 'سينمائي', en: 'Series' },
    category: 'cinema',
  },
  {
    id: 'interstellar',
    label: { ar: 'إنترستيلار (Interstellar)', en: 'Interstellar (Gargantua)' },
    description: { ar: 'ثقب غارغانتوا الدودي، أفق الحدث الذهبي، وأبعاد الفضاء والوقت النسبية.', en: 'Gargantua black hole accretion disk, relativistic gold aura, and quantum void.' },
    tone: 'interstellar',
    badge: { ar: 'سينمائي', en: 'Cinema' },
    category: 'cinema',
  },
  {
    id: 'batman-gotham',
    label: { ar: 'باتمان جوثام (The Dark Knight)', en: 'Gotham Dark Knight' },
    description: { ar: 'سماء مدينة جوثام الماطرة بسواد التيتانيوم، رمادي كربون، وأصفر بات-سيجنال الذهبي.', en: 'Rainy Gotham skyline, tactical matte titanium carbon, and Bat-Signal amber glow.' },
    tone: 'batman-gotham',
    badge: { ar: 'سينمائي', en: 'Hero' },
    category: 'cinema',
  },
  {
    id: 'outer-banks',
    label: { ar: 'أوتر بانكس (Outer Banks)', en: 'Outer Banks (OBX Paradise)' },
    description: { ar: 'غروب جزيرة كيلدير وسحر المحيط الأطلسي ببرتقالي دافئ وتركواز ساحلي مغامر.', en: 'Kildare Island golden hour, coastal surf amber, tropical turquoise, and Pogue adventures.' },
    tone: 'outer-banks',
    badge: { ar: 'سينمائي', en: 'Series' },
    category: 'cinema',
  },
  {
    id: 'game-of-thrones',
    label: { ar: 'صراع العروش (Game of Thrones)', en: 'Game of Thrones (Iron Throne)' },
    description: { ar: 'عرش ويستروس الحديدي، فحم الفاليريان، ونيران التنانين المتوهجة بذهب وياقوت تارجاريان.', en: 'Westeros Iron Throne steel, Targaryen dragon fire embers, Valyrian charcoal, and gold sigils.' },
    tone: 'game-of-thrones',
    badge: { ar: 'سينمائي', en: 'Series' },
    category: 'cinema',
  },
  {
    id: 'cyber-samurai',
    label: { ar: 'سايبر ساموراي (Cyber Samurai)', en: 'Cyber Samurai Katana' },
    description: { ar: 'حديد الكاتانا الياباني المصقول مع حواف قرمزية ساطعة وأسطح أوريغامي مظلمة.', en: 'Honed forged steel with radiant crimson katana edge and dark lacquer armor.' },
    tone: 'cyber-samurai',
    badge: { ar: 'أكشن', en: 'Samurai' },
    category: 'cinema',
  },
  {
    id: 'tokyo-night',
    label: { ar: 'طوكيو نايت (Tokyo Night)', en: 'Tokyo Night Cyber' },
    description: { ar: 'سماء طوكيو الليلية مع أضواء النيون البنفسجية والزرقاء وأسطح السايبربانك اليابانية.', en: 'Iconic Tokyo midnight blue with luminous violet and neon cyan reflections.' },
    tone: 'tokyo-night',
    badge: { ar: 'مطورين', en: 'Tokyo' },
    category: 'cyber',
  },
  {
    id: 'matrix',
    label: { ar: 'ماتريكس الطرفية الرقمية', en: 'Matrix Hacker Terminal' },
    description: { ar: 'أخضر فوسفوري كلاسيكي مستوحى من شاشات الهاكرز.', en: 'Iconic monochrome phosphor green on digital deep obsidian.' },
    tone: 'matrix',
    badge: { ar: 'كود وهاكر', en: 'Hacker' },
    category: 'cyber',
  },
  {
    id: 'monokai-pro',
    label: { ar: 'مونوكاي برو (Monokai Pro)', en: 'Monokai Pro Elite' },
    description: { ar: 'سمة المبرمجين الأسطورية بتدرجات الأوكر والوردي والفيروزي على فحم دافئ.', en: 'Legendary rich dark code theme with radiant ochre, magenta, and mint accents.' },
    tone: 'monokai-pro',
    badge: { ar: 'كود نقي', en: 'Pro Code' },
    category: 'cyber',
  },
  {
    id: 'catppuccin-mocha',
    label: { ar: 'كاتبوتشين موكا (Catppuccin)', en: 'Catppuccin Mocha' },
    description: { ar: 'لوحة مهدئة مستوحاة من ألوان الباستيل الناعمة والقهوة الداكنة المريحة جداً للعين.', en: 'Soothing dark mocha pastel palette with lavender and flamingo hues.' },
    tone: 'catppuccin-mocha',
    badge: { ar: 'باستيل مريح', en: 'Pastel' },
    category: 'cyber',
  },
  {
    id: 'dracula',
    label: { ar: 'دراكولا الليلي الشهير', en: 'Dracula Gothic Pro' },
    description: { ar: 'أزرق داكن كلاسيكي مع تدرجات زهرية وسماوية الباستيل.', en: 'Legendary developer palette with vampire slate and pastel highlights.' },
    tone: 'dracula',
    badge: { ar: 'مطورين', en: 'Dev Pick' },
    category: 'cyber',
  },
  {
    id: 'cyberpunk',
    label: { ar: 'سايبر بانك نيون', en: 'Cyberpunk Neon' },
    description: { ar: 'ألوان نيون جريئة تجمع بين الأصفر الذهبي والفيروزي.', en: 'High-octane neon yellow, cyan, and dark grid.' },
    tone: 'cyberpunk',
    badge: { ar: 'مستقبلي', en: 'Futuristic' },
    category: 'cyber',
  },
  {
    id: 'gold',
    label: { ar: 'الذهب الأسود الملكي 24k', en: 'Black Gold Luxury 24k' },
    description: { ar: 'فحم أسود راقي مع حواف وتفاصيل ذهبية عيار 24.', en: 'Ultra-luxurious titanium charcoal with burnished champagne gold.' },
    tone: 'gold',
    badge: { ar: 'نخبة', en: 'Elite' },
    category: 'luxury',
  },
  {
    id: 'emerald-luxury',
    label: { ar: 'الزمرد الملكي المخملي', en: 'Emerald Velvet Luxury' },
    description: { ar: 'خضار زمردي ياقوتي فاخر مدمج مع لمعان ذهب الشمبانيا الراقي.', en: 'Rich deep jewel-toned emerald green fused with champagne gold accents.' },
    tone: 'emerald-luxury',
    badge: { ar: 'فاخر', en: 'Luxury' },
    category: 'luxury',
  },
  {
    id: 'royal',
    label: { ar: 'أرجواني ملكي فاخر', en: 'Imperial Royal Purple' },
    description: { ar: 'بنفسجي ياقوتي مخملي لإحساس فخم وراقي.', en: 'Velvet amethyst purple with radiant lilac hints.' },
    tone: 'royal',
    badge: { ar: 'فاخر', en: 'Royal' },
    category: 'luxury',
  },
  {
    id: 'crimson',
    label: { ar: 'ياقوت قرمزي دافئ', en: 'Crimson Ruby' },
    description: { ar: 'خلفية مخملية داكنة مع توهج أحمر ياقوتي عميق.', en: 'Deep velvet noir with intense glowing crimson ruby tones.' },
    tone: 'crimson',
    badge: { ar: 'جديد', en: 'New' },
    category: 'luxury',
  },
  {
    id: 'deep-space',
    label: { ar: 'الفضاء السحيق والسديم', en: 'Deep Space Nebula' },
    description: { ar: 'سواد كوني عميق مع تدرجات سديمية كوزمية متلألئة بين الأزرق الملكي والأرجواني.', en: 'Infinite cosmic void accented with glowing stardust violet and nebula blues.' },
    tone: 'deep-space',
    badge: { ar: 'كوزميك', en: 'Cosmic' },
    category: 'luxury',
  },
  {
    id: 'aurora',
    label: { ar: 'الشفق القطبي السينمائي', en: 'Aurora Indigo' },
    description: { ar: 'تدرجات لونية مستوحاة من أضواء الشمال والبنفسج.', en: 'Deep northern lights glow with soft violet tones.' },
    tone: 'aurora',
    badge: { ar: 'سينمائي', en: 'Cinematic' },
    category: 'luxury',
  },
  {
    id: 'gruvbox-dark',
    label: { ar: 'جروف بوكس ريترو (Gruvbox)', en: 'Gruvbox Retro Dark' },
    description: { ar: 'ألوان كلاسيكية دافئة مستوحاة من ريترو التسعينيات بأخضر زيتوني وبرتقالي محروق.', en: 'Warm retro aesthetic with burnt orange, olive green, and parchment tones.' },
    tone: 'gruvbox-dark',
    badge: { ar: 'ريترو دافئ', en: 'Gruvbox' },
    category: 'nature',
  },
  {
    id: 'synthwave',
    label: { ar: 'سينث ويف ريترو 80s', en: '80s Retro Synthwave' },
    description: { ar: 'تدرج شمس الغروب النيون والماجينتا والبنفسجي الصاخب.', en: 'Neon magenta, laser sunset violet, and retro cyber-grid.' },
    tone: 'synthwave',
    badge: { ar: 'ريترو', en: 'Retro 80s' },
    category: 'nature',
  },
  {
    id: 'sunset-miami',
    label: { ar: 'غروب ميامي فايس (Miami Sunset)', en: 'Miami Vice Sunset' },
    description: { ar: 'تدرجات شواطئ ميامي النيونية بين الفوشيا الفاقع والأزرق الكاريبي الساحلي.', en: 'Vibrant neon fuchsia and turquoise ocean mist on deep palm twilight.' },
    tone: 'sunset-miami',
    badge: { ar: 'حيوي', en: 'Miami' },
    category: 'nature',
  },
  {
    id: 'ocean',
    label: { ar: 'أزرق المحيط السماوي', en: 'Deep Ocean & Cyan' },
    description: { ar: 'أزرق بحري عميق مع عناصر سماوية منعشة.', en: 'Maritime blues with vibrant cyan electric accents.' },
    tone: 'ocean',
    category: 'nature',
  },
  {
    id: 'forest',
    label: { ar: 'غابة الصنوبر والطبيعة', en: 'Deep Pine Forest' },
    description: { ar: 'خضار نباتي هادئ مستوحى من الطبيعة وغابات الصنوبر.', en: 'Earthy botanical moss green and evergreen pine serenity.' },
    tone: 'forest',
    category: 'nature',
  },
  {
    id: 'cherry-blossom',
    label: { ar: 'ساكورا كرزية يابانية (Sakura)', en: 'Cherry Blossom Sakura' },
    description: { ar: 'أزهار الساكورا الربيعية ببتلات وردية ناعمة مع لمسات فحم الكرز الداكن.', en: 'Serene Japanese spring sakura with soft blossom pinks and plum blossom noir.' },
    tone: 'cherry-blossom',
    badge: { ar: 'هادئ', en: 'Zen' },
    category: 'nature',
  },
  {
    id: 'iceberg-polar',
    label: { ar: 'جليد القطب المتجمد (Iceberg)', en: 'Polar Iceberg Glaze' },
    description: { ar: 'برودة القطب الأزرق الصقيعي النقي مع انعكاسات الجليد الشفاف والبلوري.', en: 'Glacial sub-zero cyan reflections with crisp arctic ice crystal borders.' },
    tone: 'iceberg-polar',
    badge: { ar: 'صقيعي', en: 'Glacial' },
    category: 'nature',
  },
  {
    id: 'coffee',
    label: { ar: 'قهوة ودافئ كابتشينو', en: 'Warm Coffee & Latte' },
    description: { ar: 'درجات الكاراميل والقهوة الدافئة المريحة للقراءة.', en: 'Earthy espresso and warm creamy caramel tones.' },
    tone: 'coffee',
    category: 'nature',
  },
  {
    id: 'solar',
    label: { ar: 'توهج شمس الغروب', en: 'Solar Flare & Sunset' },
    description: { ar: 'توهج عنبري ناري دافئ من أشعة الشمس وانعكاسات النحاس.', en: 'Fiery copper dusk, radiant solar amber, and warm embers.' },
    tone: 'solar',
    category: 'nature',
  },
  {
    id: 'rose',
    label: { ar: 'روز كوارتز أنيق', en: 'Rose Quartz & Blush' },
    description: { ar: 'مزيج باستيل وردي أنثوي هادئ وفاتح ومريح.', en: 'Soft pastel dusty rose with warm quartz stone aesthetics.' },
    tone: 'rose',
    badge: { ar: 'باستيل', en: 'Pastel' },
    category: 'nature',
  },
] as const;
