export type AgencyDivision = 'engineering'|'design'|'paid-media'|'sales'|'marketing'|'product'|'project-management'|'support'|'spatial-computing'|'testing'|'strategy'|'specialized';
export type AgencyCapability = 'architecture'|'frontend'|'backend'|'mobile'|'ai'|'devops'|'ui'|'ux'|'research'|'security'|'testing'|'data'|'content'|'marketing'|'sales'|'product'|'project'|'support'|'legal'|'finance'|'strategy'|'orchestration';
export interface AgencyAgent { id:string; name:string; division:AgencyDivision; description:string; capabilities:readonly AgencyCapability[]; priority:number; preferredModels?:readonly string[]; enabled:boolean; source:'agency-agents'|'adam-native'; }
export interface AgencyTeam { id:string; name:string; mission:string; divisions:readonly AgencyDivision[]; agentIds:readonly string[]; maxParallel:number; }
export interface AgencyMissionPlan { mission:string; teams:AgencyTeam[]; agents:AgencyAgent[]; parallelGroups:AgencyAgent[][]; }

const seed: AgencyAgent[] = [
 ['frontend-developer','Frontend Developer','engineering','React/Vue/Angular UI',['frontend','ui'],9],['backend-architect','Backend Architect','engineering','API, database and scalable backend',['backend','architecture'],10],['mobile-app-builder','Mobile App Builder','engineering','Native and cross-platform mobile',['mobile','architecture'],10],['ai-engineer','AI Engineer','engineering','AI integration and deployment',['ai','data'],10],['devops-automator','DevOps Automator','engineering','CI/CD and cloud operations',['devops'],9],['ui-designer','UI Designer','design','Design systems and visual interfaces',['ui'],8],['ux-researcher','UX Researcher','design','User research and usability',['ux','research'],8],['ux-architect','UX Architect','design','Implementation-ready UX architecture',['ux','architecture'],9],['security-engineer','Security Engineer','testing','Security and threat review',['security','testing'],10],['qa-engineer','QA Engineer','testing','Functional and regression testing',['testing'],9],['code-reviewer','Code Reviewer','testing','Correctness and maintainability review',['testing','architecture'],9],['researcher','Researcher','strategy','Evidence gathering and comparison',['research','strategy'],9],['fact-checker','Fact Checker','strategy','Claims and evidence verification',['research','testing'],10],['data-analyst','Data Analyst','support','Data analysis and decisions',['data'],8],['content-creator','Content Creator','marketing','Editorial and content production',['content','marketing'],7],['growth-strategist','Growth Strategist','marketing','Acquisition experiments',['marketing','strategy'],7],['product-manager','Product Manager','product','Product discovery and planning',['product','strategy'],9],['sprint-prioritizer','Sprint Prioritizer','product','Backlog prioritization',['product','project'],8],['project-shepherd','Project Shepherd','project-management','Cross-functional execution',['project','orchestration'],9],['support-responder','Support Responder','support','Customer support',['support'],7],['legal-compliance-checker','Legal Compliance Checker','support','Compliance review',['legal','research'],8],['finance-tracker','Finance Tracker','support','Financial planning',['finance','data'],7],['agents-orchestrator','Agents Orchestrator','specialized','Multi-agent coordination',['orchestration','architecture'],10],['reality-checker','Reality Checker','specialized','Challenge assumptions and failure modes',['strategy','testing'],10],
].map(([id,name,division,description,capabilities,priority])=>({id:id as string,name:name as string,division:division as AgencyDivision,description:description as string,capabilities:capabilities as AgencyCapability[],priority:priority as number,enabled:true,source:'agency-agents' as const}));

export class AgencyRegistry { private map=new Map<string,AgencyAgent>(); constructor(items:AgencyAgent[]=seed){items.forEach(x=>this.register(x));} register(x:AgencyAgent){this.map.set(x.id,x);} registerMany(xs:AgencyAgent[]){xs.forEach(x=>this.register(x));} get(id:string){return this.map.get(id);} all(){return [...this.map.values()];} enabled(){return this.all().filter(x=>x.enabled);} byDivision(d:AgencyDivision){return this.enabled().filter(x=>x.division===d);} size(){return this.map.size;} }
export const agencyRegistry=new AgencyRegistry();

export function planAgencyMission(mission:string,maxAgents=8):AgencyMissionPlan { const text=mission.toLowerCase(); const ranked=agencyRegistry.enabled().map(agent=>{const cap=agent.capabilities.filter(c=>text.includes(c)).length; const words=agent.name.toLowerCase().split(/\s+/).filter(w=>w.length>3&&text.includes(w)).length; return {agent,score:cap*5+words*2+agent.priority/10};}).sort((a,b)=>b.score-a.score); const selected=ranked.slice(0,Math.max(1,Math.min(maxAgents,20))).map(x=>x.agent); const orchestrator=agencyRegistry.get('agents-orchestrator'); if(orchestrator&&!selected.some(x=>x.id===orchestrator.id)) selected.unshift(orchestrator); const unique=[...new Map(selected.map(x=>[x.id,x])).values()]; const divisions=[...new Set(unique.map(x=>x.division))]; return {mission,teams:[{id:`mission-${Date.now()}`,name:'ADAM Mission Team',mission,divisions,agentIds:unique.map(x=>x.id),maxParallel:4}],agents:unique,parallelGroups:[unique.filter(x=>x.id==='agents-orchestrator'),unique.filter(x=>x.id!=='agents-orchestrator')]}; }
export function agencySnapshot(){return {total:agencyRegistry.size(),enabled:agencyRegistry.enabled().length,divisions:[...new Set(agencyRegistry.enabled().map(x=>x.division))]};}
