import type { FormulaCheatSheetItem } from './types';

export const COMPREHENSIVE_FORMULA_SHEETS: FormulaCheatSheetItem[] = [
  // PRIMARY / MIDDLE SCHOOL
  {
    id: 'f-geo-rect',
    category: 'Geometry',
    nameAr: 'محيط ومساحة المستطيل والمربع',
    nameEn: 'Perimeter & Area of Rectangle/Square',
    formula: 'المساحة = الطول × العرض (A = L × W) | المحيط = 2 × (L + W)',
    explanationAr: 'حساب الحيز السطحي والحدود الخارجية للأشكال الرباعية القائمة.',
    explanationEn: 'Calculate 2D surface and outer perimeter of orthogonal quadrilaterals.',
    stage: 'primary',
    exampleAr: 'مستطيل طوله 8m وعرضه 5m: المساحة = 40m² والمحيط = 26m.',
    exampleEn: 'Rectangle L=8m, W=5m: Area=40m², Perimeter=26m.',
  },
  {
    id: 'f-circle-area',
    category: 'Geometry',
    nameAr: 'محيط ومساحة الدائرة',
    nameEn: 'Circle Circumference & Area',
    formula: 'المساحة = π × r² | المحيط = 2 × π × r',
    explanationAr: 'العلاقة بين نصف القطر r ومحيط الدائرة ومساحة القرص حيث π ≈ 3.14159.',
    explanationEn: 'Relationship between radius r, perimeter, and area with constant π.',
    stage: 'middle',
    exampleAr: 'دائرة نصف قطرها r = 7cm: المساحة ≈ 154cm² والمحيط ≈ 44cm.',
    exampleEn: 'Circle radius r=7cm: Area ≈ 154cm², Circumference ≈ 44cm.',
  },
  {
    id: 'f-pythagoras',
    category: 'Geometry',
    nameAr: 'مبرهنة فيثاغورس (المثلث القائم)',
    nameEn: 'Pythagorean Theorem',
    formula: 'a² + b² = c² (مربع الوتر = مجموع مربعي الضلعين القائمين)',
    explanationAr: 'تسمح بحساب طول أي ضلع في المثلث القائم بمعرفة الضلعين الآخرين، وتأكيد التعامد.',
    explanationEn: 'Calculates hypotenuse c given legs a and b in right-angled triangles.',
    stage: 'middle',
    exampleAr: 'مثلث قائم ضلعاه 3 و 4: الوتر c = √(9 + 16) = √25 = 5.',
    exampleEn: 'Right triangle legs 3 and 4: c = √(9+16) = 5.',
  },
  {
    id: 'f-thales',
    category: 'Geometry',
    nameAr: 'مبرهنة طاليس (التناسب والتوازي)',
    nameEn: 'Thales Theorem of Proportionality',
    formula: 'AM / AB = AN / AC = MN / BC',
    explanationAr: 'تطبيق مباشر عند تقاطع مستقيمين بمستقيمين متوازيين لحساب الأطوال الناقصة.',
    explanationEn: 'Calculates unknown segment lengths in intersecting parallel lines.',
    stage: 'middle',
    exampleAr: 'إذا كان AM=3, AB=9, AN=2 فإن AC = (9×2)/3 = 6.',
    exampleEn: 'If AM=3, AB=9, AN=2 then AC = (9*2)/3 = 6.',
  },
  {
    id: 'f-ohms-law',
    category: 'Physics',
    nameAr: 'قانون أوم (الكهرباء)',
    nameEn: 'Ohm’s Law of Resistance',
    formula: 'U = R × I  (الجهد = المقاومة × شدة التيار)',
    explanationAr: 'الجهد الكهربائي بالفولت (V)، المقاومة بالأوم (Ω)، وشدة التيار بالأمبير (A).',
    explanationEn: 'Voltage U (Volts) equals Resistance R (Ohms) times Current I (Amperes).',
    stage: 'middle',
    exampleAr: 'مقاومة R = 100Ω يمر بها تيار I = 0.2A: فرق الجهد U = 20V.',
    exampleEn: 'Resistor R=100Ω with current I=0.2A yields U=20V.',
  },

  // SECONDARY / BACCALAUREATE
  {
    id: 'f-quadratic',
    category: 'Algebra',
    nameAr: 'حل المعادلة من الدرجة الثانية (المميز دلتا)',
    nameEn: 'Quadratic Equation & Discriminant Δ',
    formula: 'Δ = b² - 4ac | x₁,₂ = (-b ± √Δ) / 2a',
    explanationAr: 'إذا كان Δ > 0 حلان متمايزان، إذا كان Δ = 0 حل مضاعف x = -b/2a، إذا كان Δ < 0 لا حلول حقيقية (حلان مركبان).',
    explanationEn: 'Discriminant determines real roots: two if Δ>0, one if Δ=0, complex if Δ<0.',
    stage: 'secondary',
    exampleAr: 'x² - 5x + 6 = 0: Δ = 25 - 24 = 1 > 0، الحلان هما x=2 و x=3.',
    exampleEn: 'x² - 5x + 6 = 0: Δ = 1, roots are x=2 and x=3.',
  },
  {
    id: 'f-exp-ln',
    category: 'Calculus',
    nameAr: 'خواص الدالة الأسية واللوغاريتم الطبيعي',
    nameEn: 'Exponential & Natural Logarithm Rules',
    formula: 'e^(a+b) = e^a × e^b | ln(a×b) = ln(a) + ln(b) | ln(e^x) = x | e^(ln x) = x',
    explanationAr: 'الدوال العكسية لبعضهما البعض، أساس النهايات وحل المعادلات التفاضلية ونماذج النمو.',
    explanationEn: 'Inverse bijection pair fundamental for limits, derivatives, and ODEs.',
    stage: 'secondary',
    exampleAr: 'ln(20) = ln(4 × 5) = ln(4) + ln(5) = 2 ln(2) + ln(5).',
    exampleEn: 'ln(20) = ln(4*5) = 2*ln(2) + ln(5).',
  },
  {
    id: 'f-derivatives-table',
    category: 'Calculus',
    nameAr: 'مشتقات الدوال المركبة (قاعدة السلسلة)',
    nameEn: 'Chain Rule & Derivative Catalog',
    formula: '[u(x) × v(x)]\' = u\'v + uv\' | [u/v]\' = (u\'v - uv\') / v² | [f(u(x))]\' = u\'(x) × f\'(u(x))',
    explanationAr: 'مشتقة الدالة الأسية المركبة [e^u]\' = u\' × e^u، ومشتقة اللوغاريتم المركب [ln(u)]\' = u\' / u.',
    explanationEn: 'Product, quotient, and chain rule for compound real functions.',
    stage: 'secondary',
    exampleAr: 'مشتقة f(x) = e^(3x² + 1) هي f\'(x) = 6x × e^(3x² + 1).',
    exampleEn: 'Derivative of f(x) = e^(3x²+1) is 6x * e^(3x²+1).',
  },
  {
    id: 'f-sequences',
    category: 'Algebra',
    nameAr: 'المتتاليات الحسابية والهندسية (الحد العام والمجموع)',
    nameEn: 'Arithmetic & Geometric Sequences',
    formula: 'حسابية: U_n = U_0 + n×r | هندسية: V_n = V_0 × q^n | مجموع الحسابية: S = عدد الحدود × (الأول + الأخير)/2',
    explanationAr: 'مجموع المتتالية الهندسية: S = الحد الأول × (1 - q^n) / (1 - q) مع q ≠ 1.',
    explanationEn: 'General term & sum formula for arithmetic and geometric progressions.',
    stage: 'secondary',
    exampleAr: 'متتالية هندسية حدها الأول 2 وأساسها 3: V_4 = 2 × 3^4 = 162.',
    exampleEn: 'Geometric series V0=2, q=3: V4 = 2 * 3^4 = 162.',
  },
  {
    id: 'f-newton-second',
    category: 'Physics',
    nameAr: 'القانون الثاني لنيوتن (مبدأ التحريك الأساسي)',
    nameEn: 'Newton\'s Second Law of Motion',
    formula: 'Σ F_ext = m × a  (مجموع القوى الخارجية = الكتلة × التسارع)',
    explanationAr: 'أساس حركة الأقمار الصناعية، القذائف، المستويات المائلة، والسقوط الشاقولي مع الاحتكاك.',
    explanationEn: 'Vector sum of external forces equals mass times acceleration vector.',
    stage: 'secondary',
    exampleAr: 'جسم كتلته 2kg يتسارع بـ 3m/s²: محصلة القوى المؤثرة F = 6N.',
    exampleEn: 'Mass 2kg accelerating at 3m/s² requires net force F=6N.',
  },
  {
    id: 'f-radioactive-decay',
    category: 'Physics & Chemistry',
    nameAr: 'قانون التناقص الإشعاعي وزمن نصف العمر',
    nameEn: 'Radioactive Decay Law & Half-Life',
    formula: 'N(t) = N_0 × e^(-λt) | t_(1/2) = ln(2) / λ ≈ 0.693 / λ',
    explanationAr: 'تطور عدد الأنوية المتبقية N(t) مع الزمن، النشاط الإشعاعي A(t) = λ × N(t).',
    explanationEn: 'Exponential radioactive decay with decay constant λ and half-life t_1/2.',
    stage: 'secondary',
    exampleAr: 'عينة نصف عمرها 5 سنوات، بعد 10 سنوات (نصفي عمر) يتبقى ربع العينة (25%).',
    exampleEn: 'Sample half-life 5y: after 10y (2 half-lives), exactly 25% remains.',
  },

  // UNIVERSITY & POSTGRADUATE
  {
    id: 'f-taylor-series',
    category: 'Advanced Analysis',
    nameAr: 'منشور تايلور وماكلورين (التقريب النظري للدوال)',
    nameEn: 'Taylor & Maclaurin Series',
    formula: 'f(x) = Σ [f^(n)(a) / n!] × (x - a)^n',
    explanationAr: 'تمثيل الدوال التحليلية كمجموع لانهائي من كثيرات الحدود، وهو أساس الحساب العددي والذكاء الاصطناعي.',
    explanationEn: 'Polynomial power series expansion of infinitely differentiable functions.',
    stage: 'university',
    exampleAr: 'ماكلورين للدالة الأسية: e^x = 1 + x + x²/2! + x³/3! + ... + x^n/n!.',
    exampleEn: 'Maclaurin for e^x: 1 + x + x²/2! + x³/3! + ...',
  },
  {
    id: 'f-bayes-theorem',
    category: 'Probability & AI',
    nameAr: 'مبرهنة بايز في الاحتمال الشرطي (أساس التعلم الآلي)',
    nameEn: 'Bayes’ Theorem of Conditional Probability',
    formula: 'P(A|B) = [P(B|A) × P(A)] / P(B)',
    explanationAr: 'تحديث الاحتمال المسبق للفرضية A عند رصد الدليل الجديد B، حجر زاوية خوارزميات الذكاء الاصطناعي.',
    explanationEn: 'Updates belief in hypothesis A given new evidence B; foundation of Bayesian ML.',
    stage: 'university',
    exampleAr: 'تحديث دقة فحص طبي إيجابي بمعرفة انتشار المرض P(A) وحساسية الفحص P(B|A).',
    exampleEn: 'Medical test positive diagnostic accuracy calculated from prior disease incidence.',
  },
  {
    id: 'f-schrodinger',
    category: 'Quantum Physics',
    nameAr: 'معادلة شرودنغر المعتمدة على الزمن (ميكانيكا الكم)',
    nameEn: 'Time-Dependent Schrödinger Equation',
    formula: 'iℏ ∂Ψ/∂t = Ĥ Ψ',
    explanationAr: 'تحدد كيف تتغير الدالة الموجية Ψ للحالة الكمية للنظام مع مرور الزمن عبر مؤثر الهاميلتوني Ĥ.',
    explanationEn: 'Governs the wave function evolution of a quantum-mechanical physical system.',
    stage: 'university',
    exampleAr: 'جسيم حر في صندوق كمي أحادي البعد، مستويات الطاقة المكممة E_n = n²h² / (8mL²).',
    exampleEn: 'Particle in 1D box quantized energy states E_n = n²h² / (8mL²).',
  },
  {
    id: 'f-eigenvalues',
    category: 'Linear Algebra',
    nameAr: 'القيم والمتجهات الذاتية (Eigenvalues & Eigenvectors)',
    nameEn: 'Eigenvalues & Diagonalization',
    formula: 'A v = λ v | det(A - λI) = 0',
    explanationAr: 'إيجاد الاتجاهات التي يحافظ فيها التحويل الخطي A على اتجاه المتجه v ويكتفي بتمطيطه بالمعامل λ.',
    explanationEn: 'Finds invariant directions scaled by factor λ; foundation of PCA, SVD, and stability analysis.',
    stage: 'university',
    exampleAr: 'مصفوفة A 2x2 معادلتها المميزة λ² - 5λ + 6 = 0 تعطي القيمتين الذاتيتين λ₁=2 و λ₂=3.',
    exampleEn: 'Characteristic polynomial λ² - 5λ + 6 = 0 yields eigenvalues 2 and 3.',
  },
];
