import type { DigitalLibrary, EducationalSubject } from './types';

export const WORLD_DIGITAL_LIBRARIES: DigitalLibrary[] = [
  // 1. MEGA PREPRINTS & GENERAL ACADEMIC REPOSITORIES
  {
    id: 'openalex',
    nameAr: 'أوبن أليكس (OpenAlex)',
    nameEn: 'OpenAlex Global Index',
    category: 'preprints',
    categoryLabelAr: 'أضخم فهرس أكاديمي عالمي',
    categoryLabelEn: 'World Academic Index',
    descriptionAr: 'الفهرس المفتوح الأضخم عالمياً يضم أكثر من 250 مليون ورقة بحثية ومؤلف ومؤسسة عبر جميع التخصصات العلمية مجاناً.',
    descriptionEn: 'The world’s largest open bibliographic index indexing 250M+ scientific works, authors, and institutions.',
    estimatedVolume: '+250,000,000 بحث وكتاب',
    url: 'https://openalex.org',
    searchUrlTemplate: 'https://openalex.org/works?search={query}',
    isOpenAccess: true,
    isPeerReviewed: true,
    badge: 'Open Access 100%',
    supportedStages: ['university', 'secondary'],
    tags: ['أوراق علمية', 'جامعات', 'ذكاء اصطناعي', 'طب', 'هندسة'],
  },
  {
    id: 'arxiv',
    nameAr: 'أرشيف الأوراق العلمية (arXiv.org)',
    nameEn: 'arXiv Repository',
    category: 'stem',
    categoryLabelAr: 'الفيزياء والرياضيات والحوسبة',
    categoryLabelEn: 'Physics, Math & CS',
    descriptionAr: 'المستودع المفتوح الأول لجامعة كورنيل يضم أكثر من 2.5 مليون بحث محكم ومسبق في الرياضيات، الفيزياء، الحوسبة، وعلوم الذكاء الاصطناعي.',
    descriptionEn: 'Cornell University open-access repository for 2.5M+ scholarly articles in physics, mathematics, CS, and AI.',
    estimatedVolume: '+2,500,000 بحث',
    url: 'https://arxiv.org',
    searchUrlTemplate: 'https://arxiv.org/search/?query={query}&searchtype=all',
    isOpenAccess: true,
    isPeerReviewed: true,
    badge: 'Cornell University',
    supportedStages: ['university', 'secondary'],
    tags: ['arXiv', 'فيزياء', 'ذكاء اصطناعي', 'رياضيات', 'برمجة'],
  },
  {
    id: 'pubmed',
    nameAr: 'ببمد والمكتبة الوطنية للطب (PubMed / PMC)',
    nameEn: 'PubMed & PMC (NIH)',
    category: 'medical',
    categoryLabelAr: 'الطب وعلوم الحياة والصيدلة',
    categoryLabelEn: 'Medicine & Life Sciences',
    descriptionAr: 'أعظم مرجع طبي وبيولوجي من معاهد الصحة الوطنية الأمريكية (NIH) يضم أكثر من 36 مليون استشهاد وملايين الأبحاث الطبية الكاملة مجاناً.',
    descriptionEn: 'National Library of Medicine repository with 36M+ biomedical citations and full-text health papers.',
    estimatedVolume: '+36,000,000 بحث طبي',
    url: 'https://pubmed.ncbi.nlm.nih.gov',
    searchUrlTemplate: 'https://pubmed.ncbi.nlm.nih.gov/?term={query}',
    isOpenAccess: true,
    isPeerReviewed: true,
    badge: 'NIH / NLM US',
    supportedStages: ['university', 'secondary'],
    tags: ['طب', 'صيدلة', 'بيولوجيا', 'جراحة', 'أدوية'],
  },
  {
    id: 'core',
    nameAr: 'كور (CORE Open Access)',
    nameEn: 'CORE UK Repository',
    category: 'preprints',
    categoryLabelAr: 'مجمّع الأبحاث الأكاديمية المفتوحة',
    categoryLabelEn: 'Global Research Aggregator',
    descriptionAr: 'أضخم مجمّع عالمي للأبحاث الأكاديمية مفتوحة المصدر يربط آلاف المستودعات والجامعات حول العالم.',
    descriptionEn: 'The world’s largest aggregator of open access research papers from thousands of institutions.',
    estimatedVolume: '+260,000,000 ورقة بحثية',
    url: 'https://core.ac.uk',
    searchUrlTemplate: 'https://core.ac.uk/search?q={query}',
    isOpenAccess: true,
    isPeerReviewed: true,
    badge: 'Global Aggregator',
    supportedStages: ['university'],
    tags: ['أطروحات', 'أبحاث', 'دراسات عليا', 'جامعات'],
  },
  {
    id: 'doaj',
    nameAr: 'دليل مجلات الوصول الحر (DOAJ)',
    nameEn: 'Directory of Open Access Journals',
    category: 'preprints',
    categoryLabelAr: 'المجلات المحكمة المفتوحة',
    categoryLabelEn: 'Peer-Reviewed Journals',
    descriptionAr: 'دليل عالمي مستقل يضم أكثر من 20,000 مجلة علمية محكمة عالية الجودة تتيح أبحاثها كاملة مجاناً دون اشتراكات.',
    descriptionEn: 'Community-curated online directory indexing over 20,000 peer-reviewed, open access journals.',
    estimatedVolume: '+10,000,000 مقال محكم',
    url: 'https://doaj.org',
    searchUrlTemplate: 'https://doaj.org/search/articles?ref=homepage-box&source=%7B%22query%22%3A%7B%22query_string%22%3A%7B%22query%22%3A%22{query}%22%7D%7D%7D',
    isOpenAccess: true,
    isPeerReviewed: true,
    badge: 'Peer-Reviewed 100%',
    supportedStages: ['university', 'secondary'],
    tags: ['مجلات علمية', 'محكمة', 'أبحاث دولية'],
  },
  {
    id: 'semanticscholar',
    nameAr: 'سيمانتيك سكولار (Semantic Scholar AI)',
    nameEn: 'Semantic Scholar (Allen AI)',
    category: 'stem',
    categoryLabelAr: 'محرك بحث الأبحاث بالذكاء الاصطناعي',
    categoryLabelEn: 'AI Academic Search',
    descriptionAr: 'محرك بحث ذكي مطور من معهد ألين للذكاء الاصطناعي يستخرج خلاصات الأوراق العلمية والرسوم البيانية وتأثير الاستشهادات.',
    descriptionEn: 'Free, AI-powered research tool for scientific literature developed by the Allen Institute for AI.',
    estimatedVolume: '+215,000,000 ورقة بحثية',
    url: 'https://www.semanticscholar.org',
    searchUrlTemplate: 'https://www.semanticscholar.org/search?q={query}',
    isOpenAccess: true,
    isPeerReviewed: true,
    badge: 'Allen Institute AI',
    supportedStages: ['university'],
    tags: ['ذكاء اصطناعي', 'تحليل الاستشهادات', 'أوراق علمية'],
  },

  // 2. WORLD MEGA LIBRARIES, CLASSIC BOOKS & DIGITAL ARCHIVES
  {
    id: 'internetarchive',
    nameAr: 'أرشيف الإنترنت والمكتبة المفتوحة (Internet Archive / Open Library)',
    nameEn: 'Internet Archive & Open Library',
    category: 'books',
    categoryLabelAr: 'أعظم مكتبة رقمية في التاريخ',
    categoryLabelEn: 'World Digital Heritage',
    descriptionAr: 'مكتبة غير ربحية تحتوي ملايين الكتب المجانية، المخطوطات النادرة، التسجيلات الصوتية، ومقاطع الفيديو التاريخية المتاحة للجميع.',
    descriptionEn: 'Digital library of millions of free books, movies, software, music, websites, and historical manuscripts.',
    estimatedVolume: '+44,000,000 كتاب ومادة',
    url: 'https://archive.org',
    searchUrlTemplate: 'https://archive.org/search.php?query={query}',
    isOpenAccess: true,
    isPeerReviewed: false,
    badge: 'Universal Access',
    supportedStages: ['primary', 'middle', 'secondary', 'university'],
    tags: ['كتب تاريخية', 'مخطوطات', 'أرشيف', 'تراث'],
  },
  {
    id: 'gutenberg',
    nameAr: 'مشروع غوتنبرغ (Project Gutenberg)',
    nameEn: 'Project Gutenberg',
    category: 'books',
    categoryLabelAr: 'أمهات الكتب والأدب الكلاسيكي',
    categoryLabelEn: 'Classic Literature & eBooks',
    descriptionAr: 'أقدم وأشهر مكتبة رقمية في العالم تتيح أكثر من 70,000 كتاب إلكتروني مجاني كامل في الأدب، الفلسفة، التاريخ، والعلوم.',
    descriptionEn: 'A library of over 70,000 free eBooks focusing on the world’s greatest classic literature and historical texts.',
    estimatedVolume: '+73,000 كتاب كامل',
    url: 'https://www.gutenberg.org',
    searchUrlTemplate: 'https://www.gutenberg.org/ebooks/search/?query={query}',
    isOpenAccess: true,
    isPeerReviewed: false,
    badge: 'Free eBooks Forever',
    supportedStages: ['middle', 'secondary', 'university'],
    tags: ['أدب عالمي', 'فلسفة', 'تاريخ', 'روايات'],
  },
  {
    id: 'wdl',
    nameAr: 'المكتبة الرقمية العالمية (World Digital Library - UNESCO)',
    nameEn: 'World Digital Library (UNESCO / LOC)',
    category: 'humanities',
    categoryLabelAr: 'التراث الإنساني ومكتبة الكونغرس واليونسكو',
    categoryLabelEn: 'UNESCO Cultural Heritage',
    descriptionAr: 'مشروع مشترك بين اليونسكو ومكتبة الكونغرس الأمريكية يتيح الوصول الحر لمخطوطات وخرائط وكتب نادرة من مختلف حضارات العالم بلغات متعددة.',
    descriptionEn: 'UNESCO and Library of Congress initiative providing free access to rare manuscripts, maps, and historical books.',
    estimatedVolume: '+20,000 مخطوطة ووثيقة نادرة',
    url: 'https://www.loc.gov/collections/world-digital-library/',
    searchUrlTemplate: 'https://www.loc.gov/collections/world-digital-library/?q={query}',
    isOpenAccess: true,
    isPeerReviewed: true,
    badge: 'UNESCO & Library of Congress',
    supportedStages: ['middle', 'secondary', 'university'],
    tags: ['مخطوطات', 'تاريخ', 'جغرافيا', 'حضارات'],
  },
  {
    id: 'bibalex',
    nameAr: 'مستودع مكتبة الإسكندرية الرقمي (Bibliotheca Alexandrina)',
    nameEn: 'Bibliotheca Alexandrina Digital Assets',
    category: 'humanities',
    categoryLabelAr: 'المكتبة العربية والعالمية الكبرى',
    categoryLabelEn: 'Arabic & World Heritage',
    descriptionAr: 'مستودع الأصول الرقمية لمكتبة الإسكندرية، يوفر مئات الآلاف من الكتب والمراجع العربية والمترجمة النادرة والحديثة.',
    descriptionEn: 'Digital repository of the Library of Alexandria, providing vast Arabic and international literature.',
    estimatedVolume: '+300,000 كتاب عربي وعالمي',
    url: 'https://dar.bibalex.org',
    searchUrlTemplate: 'https://dar.bibalex.org/#/Search?query={query}',
    isOpenAccess: true,
    isPeerReviewed: true,
    badge: 'Heritage & Science',
    supportedStages: ['secondary', 'university'],
    tags: ['مراجع عربية', 'تاريخ إسلامي', 'فكر', 'علوم'],
  },
  {
    id: 'googlebooks',
    nameAr: 'كتب جوجل الأكاديمية (Google Books & Scholar)',
    nameEn: 'Google Scholar & Books',
    category: 'books',
    categoryLabelAr: 'محرك الكتب والأبحاث العالمي',
    categoryLabelEn: 'Global Books & Scholar',
    descriptionAr: 'محرك بحث متكامل يغطي مئات الملايين من الكتب والمعاينات والاستشهادات العلمية والرسائل الجامعية.',
    descriptionEn: 'Comprehensive index for full text and metadata of scholarly literature and digitized books.',
    estimatedVolume: '+40,000,000 كتاب ومرجع',
    url: 'https://scholar.google.com',
    searchUrlTemplate: 'https://scholar.google.com/scholar?q={query}',
    isOpenAccess: false,
    isPeerReviewed: true,
    badge: 'Universal Search',
    supportedStages: ['secondary', 'university'],
    tags: ['جوجل سكولار', 'استشهادات', 'كتب'],
  },

  // 3. FREE TEXTBOOKS & CURRICULUMS (K-12 & HIGHER ED)
  {
    id: 'openstax',
    nameAr: 'أوبن ستاكس للكتب الجامعية المجانية (OpenStax - Rice University)',
    nameEn: 'OpenStax Free College Textbooks',
    category: 'courses',
    categoryLabelAr: 'الكتب الدراسية الجامعية المحكمة مجاناً',
    categoryLabelEn: 'Peer-Reviewed College Textbooks',
    descriptionAr: 'مبادرة جامعة رايس الأمريكية لتوفير كتب دراسية جامعية كاملة ومحكمة 100% مجاناً في الفيزياء، الرياضيات، الكيمياء، الاقتصاد، والبيولوجيا.',
    descriptionEn: 'Rice University nonprofit educational initiative publishing free, peer-reviewed, openly licensed college textbooks.',
    estimatedVolume: '+100 كتاب دراسي جامعي ضخم',
    url: 'https://openstax.org',
    searchUrlTemplate: 'https://openstax.org/subjects',
    isOpenAccess: true,
    isPeerReviewed: true,
    badge: 'Rice University Free',
    supportedStages: ['secondary', 'university'],
    tags: ['كتب مقررات', 'تفاضل وتكامل', 'فيزياء', 'كيمياء', 'أحياء'],
  },
  {
    id: 'khanacademy',
    nameAr: 'أكاديمية خان (Khan Academy - عربي وإنجليزي)',
    nameEn: 'Khan Academy (All Grades)',
    category: 'k12',
    categoryLabelAr: 'المناهج المدرسية من الابتدائي إلى الثانوي',
    categoryLabelEn: 'Complete K-12 Curriculum',
    descriptionAr: 'المنصة التعليمية الأولى عالمياً التي تقدم دروساً تفاعلية وتمارين تغطي كامل المناهج المدرسية (رياضيات، علوم، برمجة، تاريخ) من الروضة إلى البكالوريا.',
    descriptionEn: 'World-renowned personalized learning resource offering free lessons and interactive exercises from kindergarten to early college.',
    estimatedVolume: '+10,000 درس تفاعلي مجاني',
    url: 'https://ar.khanacademy.org',
    searchUrlTemplate: 'https://ar.khanacademy.org/search?page_search_query={query}',
    isOpenAccess: true,
    isPeerReviewed: true,
    badge: 'K-12 Mastery',
    supportedStages: ['primary', 'middle', 'secondary'],
    tags: ['ابتدائي', 'متوسط', 'ثانوي', 'رياضيات', 'علوم'],
  },
  {
    id: 'mitocw',
    nameAr: 'مقررات معهد ماساتشوستس للتقنية المفتوحة (MIT OpenCourseWare)',
    nameEn: 'MIT OpenCourseWare (OCW)',
    category: 'courses',
    categoryLabelAr: 'محاضرات ومناهج MIT كاملة مجاناً',
    categoryLabelEn: 'Full MIT Courses Free',
    descriptionAr: 'نشر إلكتروني مجاني ومفتوح لجميع مواد ومحاضرات وتمارين معهد MIT العالمي في الهندسة، الحاسوب، الرياضيات، والفيزياء.',
    descriptionEn: 'Web-based publication of virtually all MIT course content, freely accessible to learners worldwide.',
    estimatedVolume: '+2,500 كورس جامعي متكامل',
    url: 'https://ocw.mit.edu',
    searchUrlTemplate: 'https://ocw.mit.edu/search/?q={query}',
    isOpenAccess: true,
    isPeerReviewed: true,
    badge: 'MIT Official',
    supportedStages: ['secondary', 'university'],
    tags: ['MIT', 'هندسة', 'برمجة', 'فيزياء كمية', 'حساب التفاضل'],
  },
  {
    id: 'phet',
    nameAr: 'محاكاة العلوم والفيزياء التفاعلية (PhET Simulations)',
    nameEn: 'PhET Interactive Simulations (Colorado)',
    category: 'k12',
    categoryLabelAr: 'المختبر الافتراضي للفيزياء والكيمياء',
    categoryLabelEn: 'Virtual STEM Laboratory',
    descriptionAr: 'مشروع جامعة كولورادو الحائز على جوائز يوفر مختبرات تفاعلية ومحاكاة رسومية للفيزياء، الكيمياء، الرياضيات، والبيولوجيا لكافة الأطوار.',
    descriptionEn: 'University of Colorado interactive simulations for science and math, supporting inquiry-based learning for all grades.',
    estimatedVolume: '+160 مختبر افتراضي تفاعلي',
    url: 'https://phet.colorado.edu/ar_SA',
    searchUrlTemplate: 'https://phet.colorado.edu/ar_SA/simulations/browse?search={query}',
    isOpenAccess: true,
    isPeerReviewed: true,
    badge: 'Interactive Lab',
    supportedStages: ['primary', 'middle', 'secondary', 'university'],
    tags: ['تجارب فيزياء', 'كيمياء', 'محاكاة', 'تفاعلي'],
  },
  {
    id: 'wolframmathworld',
    nameAr: 'موسوعة وولفرام للرياضيات (Wolfram MathWorld)',
    nameEn: 'Wolfram MathWorld',
    category: 'stem',
    categoryLabelAr: 'المرجع الرياضي الأشمل في العالم',
    categoryLabelEn: 'Comprehensive Math Resource',
    descriptionAr: 'الموسوعة الرياضية الأشمل والأدق عالمياً، التي تجمع آلاف المقالات التفصيلية حول المعادلات والنظريات والبراهين من الابتدائي إلى ما بعد الدكتوراه.',
    descriptionEn: 'The web’s most extensive mathematical resource, provided as a free service by Wolfram Research.',
    estimatedVolume: '+13,000 مدخل ومفهوم رياضي',
    url: 'https://mathworld.wolfram.com',
    searchUrlTemplate: 'https://mathworld.wolfram.com/search/?query={query}',
    isOpenAccess: true,
    isPeerReviewed: true,
    badge: 'Wolfram Research',
    supportedStages: ['middle', 'secondary', 'university'],
    tags: ['رياضيات', 'معادلات', 'تكامل', 'جبر', 'هندسة'],
  },
  {
    id: 'ssrn',
    nameAr: 'شبكة أبحاث العلوم الاجتماعية والاقتصاد (SSRN)',
    nameEn: 'Social Science Research Network',
    category: 'humanities',
    categoryLabelAr: 'الاقتصاد والقانون والعلوم الإدارية',
    categoryLabelEn: 'Economics, Law & Social Sciences',
    descriptionAr: 'المستودع الأكبر في العالم للأبحاث الأكاديمية المبكرة في الاقتصاد، التمويل، القانون، العلوم السياسية، وإدارة الأعمال.',
    descriptionEn: 'Leading social science and humanities research repository sharing pre-publication research worldwide.',
    estimatedVolume: '+1,200,000 ورقة بحثية',
    url: 'https://www.ssrn.com',
    searchUrlTemplate: 'https://www.ssrn.com/index.cfm/en/search/?q={query}',
    isOpenAccess: true,
    isPeerReviewed: true,
    badge: 'Elsevier Network',
    supportedStages: ['university'],
    tags: ['اقتصاد', 'قانون', 'إدارة أعمال', 'سياسة'],
  },
  {
    id: 'biorxiv',
    nameAr: 'بايو أركايف و كيم أركايف (bioRxiv & ChemRxiv)',
    nameEn: 'bioRxiv & ChemRxiv Preprints',
    category: 'stem',
    categoryLabelAr: 'الكيمياء وعلوم الأحياء الدقيقة',
    categoryLabelEn: 'Biology & Chemistry Preprints',
    descriptionAr: 'المستودعات الأكاديمية الأولى في العالم المخصصة لنشر أحدث الاكتشافات في علم الأحياء والوراثة والكيمياء المتقدمة قبل الطباعة.',
    descriptionEn: 'Cold Spring Harbor Laboratory open archive for life sciences and chemistry research papers.',
    estimatedVolume: '+250,000 بحث طليعي',
    url: 'https://www.biorxiv.org',
    searchUrlTemplate: 'https://www.biorxiv.org/search/{query}',
    isOpenAccess: true,
    isPeerReviewed: true,
    badge: 'Cold Spring Harbor',
    supportedStages: ['university'],
    tags: ['بيولوجيا', 'جينات', 'كيمياء حيوية', 'صيدلة'],
  },
  {
    id: 'wikisource',
    nameAr: 'ويكي مصدر والمكتبة الحرة (Wikisource & Wikipedia)',
    nameEn: 'Wikisource Free Library',
    category: 'books',
    categoryLabelAr: 'نصوص الوثائق الأصلية والكتب المجانية',
    categoryLabelEn: 'Open Source Documents',
    descriptionAr: 'مكتبة حرة للنصوص والوثائق التاريخية والمصادر الأولية في الملكية العامة بمختلف لغات العالم، بما فيها مئات آلاف الكتب العربية.',
    descriptionEn: 'Online digital library of free-content textual sources and historical documents in all languages.',
    estimatedVolume: '+5,000,000 نص ووثيقة',
    url: 'https://ar.wikisource.org',
    searchUrlTemplate: 'https://ar.wikisource.org/w/index.php?search={query}',
    isOpenAccess: true,
    isPeerReviewed: false,
    badge: 'Wikimedia Free',
    supportedStages: ['primary', 'middle', 'secondary', 'university'],
    tags: ['كتب تراث', 'وثائق تاريخية', 'أشعار', 'نصوص أصلية'],
  },
  {
    id: 'europeana',
    nameAr: 'يوروبيانا (Europeana Cultural Collections)',
    nameEn: 'Europeana Collections',
    category: 'humanities',
    categoryLabelAr: 'المكتبة الرقمية الأوروبية الموحدة',
    categoryLabelEn: 'European Cultural Heritage',
    descriptionAr: 'المنصة الرقمية للاتحاد الأوروبي التي تربط أكثر من 3000 مكتبة ومتحف وأرشيف وطني عبر القارة الأوروبية مع ملايين المواد القابلة للبحث.',
    descriptionEn: 'EU digital platform empowering cultural heritage with 50M+ digitized books, artworks, and archival records.',
    estimatedVolume: '+50,000,000 مادة ثقافية',
    url: 'https://www.europeana.eu',
    searchUrlTemplate: 'https://www.europeana.eu/en/search?query={query}',
    isOpenAccess: true,
    isPeerReviewed: true,
    badge: 'European Union Hub',
    supportedStages: ['middle', 'secondary', 'university'],
    tags: ['تاريخ أوروبي', 'فن', 'مخطوطات', 'خرائط'],
  }
];

export const STAGE_CURRICULUM_DATA: EducationalSubject[] = [
  // 1. PRIMARY STAGE (الطور الابتدائي)
  {
    id: 'primary-math',
    titleAr: 'الرياضيات التأسيسية والحساب الممتع',
    titleEn: 'Foundational Math & Arithmetic',
    icon: 'Calculator',
    stage: 'primary',
    descriptionAr: 'العمليات الأربع، الكسور البسيطة، قياس الأشكال، الأنماط، وحل المسائل الذهنية المسلية.',
    descriptionEn: 'Basic operations, simple fractions, shapes, patterns, and fun mental arithmetic.',
    topics: [
      {
        titleAr: 'جدول الضرب وتقنيات الحساب السريع',
        titleEn: 'Multiplication Tables & Mental Math',
        summaryAr: 'فهم الضرب كجمع متكرر، حيل الحفظ السريع لجداول 6 و 7 و 8 و 9، وتطبيقها في الحياة اليومية.',
        summaryEn: 'Understanding multiplication as repeated addition, tricks for 6, 7, 8, 9 tables.',
        keyPointsAr: ['الضرب هو تكرار الجمع', 'خاصية التبديل: 4 × 7 هي نفسها 7 × 4', 'الضرب في 10 يضيف صفراً'],
        keyPointsEn: ['Multiplication is repeated addition', 'Commutative property: 4x7 = 7x4', 'Multiplying by 10 adds a zero'],
        practicePrompt: 'اشرح لي جدول الضرب بطريقة كرتونية وقصصية مبسطة كأنني في الصف الثالث الابتدائي.',
      },
      {
        titleAr: 'الكسور والأشكال الهندسية الأساسية',
        titleEn: 'Fractions & Fundamental Geometry',
        summaryAr: 'النصف والربع والثمن باستخدام مثال البيتزا والرغيف، وحساب محيط ومساحة المربع والمستطيل.',
        summaryEn: 'Halves, quarters, eighths with pizza models, perimeter and area of rectangle and square.',
        keyPointsAr: ['البسط يعبر عن الجزء والمقام يعبر عن الكل', 'المحيط = مجموع أطوال الأضلاع', 'المساحة = الطول × العرض'],
        keyPointsEn: ['Numerator is parts, denominator is total', 'Perimeter = sum of sides', 'Area = length x width'],
        practicePrompt: 'كيف أشرح لطفل في الابتدائي مفهوم الكسر العشري والأشكال الهندسية؟',
      },
    ],
    referenceLinks: [
      { title: 'تمارين رياضيات الابتدائي - أكاديمية خان', url: 'https://ar.khanacademy.org/math/k-8-grades', type: 'interactive' },
      { title: 'ألعاب الرياضيات التفاعلية للأطفال', url: 'https://www.mathplayground.com', type: 'interactive' },
    ],
  },
  {
    id: 'primary-science',
    titleAr: 'العلوم والاكتشاف والحياة',
    titleEn: 'Elementary Science & Nature',
    icon: 'Compass',
    stage: 'primary',
    descriptionAr: 'جسم الإنسان، دورة حياة النباتات والحيوانات، حالات المادة الثلاث، وحماية البيئة.',
    descriptionEn: 'Human body, plant and animal life cycles, three states of matter, and the environment.',
    topics: [
      {
        titleAr: 'حالات المادة الثلاث: صلبة وسائلة وغازية',
        titleEn: 'Three States of Matter: Solid, Liquid, Gas',
        summaryAr: 'تحول الماء بين الثلج والسائل والبخار، مفهوم التبخر والتكثف والتجمد بطريقة تجريبية.',
        summaryEn: 'Phase transitions of water: ice, liquid, and steam through everyday home experiments.',
        keyPointsAr: ['المادة الصلبة لها شكل ثابت', 'السائل يأخذ شكل الإناء', 'الغاز ينتشر في كل مكان'],
        keyPointsEn: ['Solids keep shape', 'Liquids take container shape', 'Gases expand everywhere'],
        practicePrompt: 'ما هي دورة الماء في الطبيعة وكيف تحدث الأمطار للأطفال؟',
      },
    ],
    referenceLinks: [
      { title: 'تجارب تفاعلية للأطفال - PhET', url: 'https://phet.colorado.edu/ar_SA/simulations/filter?subjects=elementary-school', type: 'interactive' },
    ],
  },

  // 2. MIDDLE SCHOOL STAGE (الطور المتوسط / الإعدادي)
  {
    id: 'middle-algebra',
    titleAr: 'الجبر والهندسة المستوية',
    titleEn: 'Algebra & Plane Geometry',
    icon: 'Binary',
    stage: 'middle',
    descriptionAr: 'المعادلات من الدرجة الأولى، نظرية فيثاغورس، طاليس، الإحصاء والاحتمالات البسيطة.',
    descriptionEn: 'Linear equations, Pythagorean theorem, Thales theorem, basic statistics, and probabilities.',
    topics: [
      {
        titleAr: 'نظرية فيثاغورس وحساب المثلثات القائمة',
        titleEn: 'Pythagorean Theorem & Right Triangles',
        summaryAr: 'مربع طول الوتر يساوي مجموع مربعي طولي الضلعين القائمين (a² + b² = c²)، واستخدامها لحساب الأطوال الناقصة.',
        summaryEn: 'Hypotenuse square equals sum of squares of the other two sides (a² + b² = c²).',
        keyPointsAr: ['تنطبق فقط على المثلث القائم', 'الوتر هو أطول ضلع ويقابل الزاوية القائمة', 'النظرية العكسية تثبت إن كان المثلث قائماً'],
        keyPointsEn: ['Applies only to right-angled triangles', 'Hypotenuse opposes the right angle', 'Converse proves right-angledness'],
        practicePrompt: 'حل مسألة: مثلث قائم ضلعي زاويته القائمة 6 سم و 8 سم، احسب طول الوتر بالخطوات.',
      },
      {
        titleAr: 'حل جمل المعادلات الخطية بمجهولين',
        titleEn: 'Systems of Linear Equations',
        summaryAr: 'طريقة التعويض وطريقة الجمع لحل معادلتين بمجهولين x و y وتفسيرها هندسياً كنقطة تقاطع مستقيمين.',
        summaryEn: 'Substitution and elimination methods for solving two-variable linear systems.',
        keyPointsAr: ['طريقة التعويض: عزل مجهول في إحدى المعادلتين', 'طريقة الجمع: توحيد المعاملات وحذف أحد المجاهيل', 'الحل هو إحداثيات نقطة التقاطع'],
        keyPointsEn: ['Substitution: isolate one variable', 'Elimination: match coefficients', 'Solution is intersection point'],
        practicePrompt: 'اشرح بالخطوات كيفية حل الجملة: 2x + y = 10 و x - y = 2.',
      },
    ],
    referenceLinks: [
      { title: 'جبر التعليم المتوسط - Khan Academy', url: 'https://ar.khanacademy.org/math/algebra-basics', type: 'interactive' },
    ],
  },
  {
    id: 'middle-physics',
    titleAr: 'العلوم الفيزيائية والمادة وتحولاتها',
    titleEn: 'Physical Science & Chemical Reactions',
    icon: 'Atom',
    stage: 'middle',
    descriptionAr: 'الدارة الكهربائية، قانون أوم، التحول الكيميائي والفيزيائي، والذرات والجزيئات.',
    descriptionEn: 'Electric circuits, Ohm’s law, chemical vs physical changes, atoms and molecules.',
    topics: [
      {
        titleAr: 'الكهرباء والمقادير الكهربائية (التيار والتوتر والمقاومة)',
        titleEn: 'Electric Circuits: Current, Voltage, Resistance',
        summaryAr: 'قانون أوم (U = R × I)، قياس شدة التيار بالأمبير والتوتر بالفولت، وربط المقاومات على التوالي والتفرع.',
        summaryEn: 'Ohm’s law (U = R × I), ammeter and voltmeter usage, series and parallel circuits.',
        keyPointsAr: ['قانون أوم: U = R × I', 'على التوالي: شدة التيار ثابتة والتوتر ينقسم', 'على التفرع: التوتر ثابت والتيار ينقسم'],
        keyPointsEn: ['Ohm’s Law: U = R x I', 'Series: current constant, voltage divides', 'Parallel: voltage constant, current divides'],
        practicePrompt: 'مقاومة قيمتها 20 أوم يمر بها تيار شدته 0.5 أمبير، ما قيمة التوتر الكهربائي بين طرفيها؟',
      },
    ],
    referenceLinks: [
      { title: 'محاكاة الدارات الكهربائية - PhET', url: 'https://phet.colorado.edu/ar_SA/simulations/circuit-construction-kit-dc', type: 'interactive' },
    ],
  },

  // 3. SECONDARY & BACCALAUREATE STAGE (الطور الثانوي / البكالوريا)
  {
    id: 'sec-advanced-math',
    titleAr: 'الرياضيات المتقدمة والبكالوريا',
    titleEn: 'Advanced Mathematics & Baccalaureate',
    icon: 'Sigma',
    stage: 'secondary',
    descriptionAr: 'الدوال العددية (الأسية واللوغاريتمية)، النهايات، الاشتقاق، التكامل، المتتاليات العددية، والاحتمالات.',
    descriptionEn: 'Calculus (limits, derivatives, integrals), exponential & logarithmic functions, sequences, and probability.',
    topics: [
      {
        titleAr: 'دراسة الدوال الأسية واللوغاريتمية والنهايات',
        titleEn: 'Exponential & Logarithmic Functions & Limits',
        summaryAr: 'خواص الدالة e^x و ln(x)، إزالة حالات عدم التعيين الأربع، المشتقات ودراسة إشارة التغيرات ورسم المنحنى البياني.',
        summaryEn: 'Properties of e^x and ln(x), indeterminate forms, derivatives, inflection points, and curve plotting.',
        keyPointsAr: ['حالات عدم التعيين: 0/0, ∞/∞, 0×∞, +∞-∞', 'مشتق الدالة الأسية المركبة: (e^u)\' = u\' × e^u', 'مشتق اللوغاريتم: (ln u)\' = u\' / u'],
        keyPointsEn: ['Indeterminate forms: 0/0, inf/inf, 0xinf, inf-inf', 'Derivative of e^u is u\'*e^u', 'Derivative of ln(u) is u\'/u'],
        practicePrompt: 'احسب نهاية الدالة f(x) = (e^x - 1)/x عندما يؤول x إلى 0 بالخطوات والتعليل.',
      },
      {
        titleAr: 'المتتاليات الحسابية والهندسية والبرهان بالتراجع',
        titleEn: 'Arithmetic & Geometric Sequences & Induction',
        summaryAr: 'عبارة الحد العام، المجموع، التقارب، ومبدأ الاستدلال بالتراجع لإثبات صحة الخصائص الرياضية لكل عدد طبيعي n.',
        summaryEn: 'General term, sum of terms, convergence, and mathematical induction proofs for all natural numbers.',
        keyPointsAr: ['المتتالية الحسابية: Un = U0 + n*r', 'المتتالية الهندسية: Un = U0 * q^n', 'مراحل البرهان بالتراجع: التحقق ثم الفرض ثم البرهان'],
        keyPointsEn: ['Arithmetic: Un = U0 + n*r', 'Geometric: Un = U0 * q^n', 'Induction steps: base case, induction hypothesis, inductive step'],
        practicePrompt: 'اشرح خطوات البرهان بالتراجع لحل مسألة بكالوريا مع نموذج تطبيقي.',
      },
    ],
    referenceLinks: [
      { title: 'مقرر التفاضل والتكامل المفتوح - OpenStax Calculus', url: 'https://openstax.org/details/books/calculus-volume-1', type: 'book' },
      { title: 'وولفرام لحل المعادلات الرياضية بالخطوات', url: 'https://www.wolframalpha.com', type: 'platform' },
    ],
  },
  {
    id: 'sec-physics-chemistry',
    titleAr: 'الفيزياء الميكانيكية والكيمياء العضوية',
    titleEn: 'Mechanics, Electromagnetism & Organic Chemistry',
    icon: 'Cpu',
    stage: 'secondary',
    descriptionAr: 'قوانين نيوتن في الميكانيكا، حركة الكواكب والأقمار، التحولات النووية، والظواهر الكهربائية (RC و RL)، وتفاعلات الأسترة.',
    descriptionEn: 'Newtonian mechanics, planetary motion, nuclear reactions, RC/RL circuits, and organic chemistry (esterification).',
    topics: [
      {
        titleAr: 'قوانين نيوتن وحركة السقوط الشاقولي والقذائف',
        titleEn: 'Newton’s Laws & Projectile Motion',
        summaryAr: 'القانون الثاني لنيوتن (∑F = m·a)، معادلات الحركة، السرعة اللحظية، الإسقاط على المحاور، ومعادلة المسار.',
        summaryEn: 'Newton’s second law, kinematic equations, projectile velocity components, and trajectory equations.',
        keyPointsAr: ['القانون الثاني: مجموع القوى الخارجية يساوي الكتلة في التسارع', 'تسارع الجاذبية الأرضية g شاقولي نحو الأسفل', 'معادلة المسار هي دالة من الدرجة الثانية (قطع مكافئ)'],
        keyPointsEn: ['F = m*a', 'Gravity points vertically down', 'Trajectory is a parabolic curve'],
        practicePrompt: 'اكتب المعادلة التفاضلية لحركة مركز عطالة جسم يسقط سقوطاً حقيقياً في الهواء مع الاحتكاك f = -k·v.',
      },
    ],
    referenceLinks: [
      { title: 'مقرر فيزياء الكليات المفتوح - OpenStax University Physics', url: 'https://openstax.org/details/books/university-physics-volume-1', type: 'book' },
    ],
  },
  {
    id: 'sec-philosophy-arabic',
    titleAr: 'الفلسفة ومنهجيات المقال والتحليل',
    titleEn: 'Philosophy, Critical Thought & Essay Writing',
    icon: 'BookOpen',
    stage: 'secondary',
    descriptionAr: 'منهجية المقالة الفلسفية (المقارنة، الجدلية، الاستقصاء بالوضع)، المذاهب الفكرية، فلسفة العلوم، والإشكالات الكبرى.',
    descriptionEn: 'Dialectical philosophical essay methodology, epistemology, ethics, philosophy of science, and critical analysis.',
    topics: [
      {
        titleAr: 'منهجية كتابة المقالة الجدلية في الفلسفة',
        titleEn: 'Methodology of Dialectical Philosophical Essays',
        summaryAr: 'طرح المشكلة (المقدمة وضبط المفاهيم)، عرض الأطروحة الأولى وحججها ونقدها، عرض نقيض الأطروحة وحججه ونقده، التركيب أو التجاوز، ثم الخاتمة.',
        summaryEn: 'Introduction & problem statement, Thesis & arguments, Antithesis & rebuttal, Synthesis/Transcendence, and Conclusion.',
        keyPointsAr: ['المقدمة: التمهيد الوظيفي، العناد الفلسفي، وطرح التساؤل بدقة', 'الجدل يتطلب حججاً فلسفية وأمثلة واقعية ونقداً موضوعياً', 'التركيب هو بناء موقف توفيقي وليس مجرد جمع'],
        keyPointsEn: ['Intro: context, conflict, problem statement', 'Arguments require philosophers and real examples', 'Synthesis resolves thesis-antithesis'],
        practicePrompt: 'اكتب لي مخططاً نموذجياً لمقالة فلسفية جدلية حول: "هل لكل سؤال علمي جواب بالضرورة؟".',
      },
    ],
    referenceLinks: [
      { title: 'موسوعة ستانفورد للفلسفة (Stanford Encyclopedia of Philosophy)', url: 'https://plato.stanford.edu', type: 'platform' },
    ],
  },

  // 4. UNIVERSITY & POSTGRADUATE RESEARCH STAGE (الطور الجامعي والبحث العلمي)
  {
    id: 'uni-research-methodology',
    titleAr: 'منهجية البحث العلمي ومذكرات التخرج',
    titleEn: 'Scientific Research Methodology & Dissertations',
    icon: 'GraduationCap',
    stage: 'university',
    descriptionAr: 'صياغة إشكالية البحث، مراجعة الأدبيات السابقة (Literature Review)، التحليل الإحصائي، وأساليب الاقتباس الأكاديمي (APA, IEEE, Harvard).',
    descriptionEn: 'Research problem definition, literature review, statistical methodologies, thesis framing, and citation standards.',
    topics: [
      {
        titleAr: 'هيكلة مذكرة الماستر وأطروحة الدكتوراه من الألف إلى الياء',
        titleEn: 'Master’s Thesis & Doctoral Dissertation Architecture',
        summaryAr: 'العناصر الإلزامية: الملخص (Abstract)، المقدمة والإشكالية، الدراسات السابقة، المنهجية (Methodology)، النتائج، المناقشة، والخاتمة وقائمة المراجع.',
        summaryEn: 'Core structure: Abstract, Introduction & research question, Literature Review, Methodology, Results, Discussion, and Bibliography.',
        keyPointsAr: ['الإشكالية يجب أن تكون واضحة وقابلة للقياس والبحث', 'مراجعة الأدبيات تبرز الفجوة البحثية (Research Gap)', 'المناقشة تفسر الأسباب وراء النتائج وتقارنها بالأبحاث السابقة'],
        keyPointsEn: ['Problem must be measurable and bounded', 'Literature review reveals research gap', 'Discussion compares findings to existing theory'],
        practicePrompt: 'كيف أكتب ملخصاً احترافياً (Abstract) لبحث تخرجي الجامعي يجذب لجان التحكيم؟',
      },
      {
        titleAr: 'قواعد التوثيق الأكاديمي وصيغ المراجع (APA 7th & IEEE)',
        titleEn: 'Academic Citation Standards (APA 7th, IEEE, MLA)',
        summaryAr: 'كيفية توثيق المقالات العلمية، الكتب، المؤتمرات، والمواقع الرسمية في المتن وفي قائمة المصادر والمراجع دون أي نسبة انتحال (Plagiarism).',
        summaryEn: 'How to cite articles, books, proceedings, and datasets in-text and in reference lists without plagiarism.',
        keyPointsAr: ['APA 7th: يعتمد على المؤلف والسنة (Smith, 2024)', 'IEEE: يعتمد على الترقيم بين معقوفتين [1]', 'ضرورة وضع رقم DOI لجميع الأوراق الرقمية'],
        keyPointsEn: ['APA 7th: Author-Date system', 'IEEE: Numerical bracketed citation [1]', 'Always include DOI when available'],
        practicePrompt: 'حول هذا المرجع إلى صيغة APA 7th وصيغة IEEE: كتاب الذكاء الاصطناعي لمؤلفيه ستيوارت راسل وبيتر نورفيغ سنة 2020.',
      },
    ],
    referenceLinks: [
      { title: 'دليل جامعة بوردو للتوثيق الأكاديمي (Purdue OWL)', url: 'https://owl.purdue.edu', type: 'platform' },
      { title: 'أداة البحث المفتوح عن المراجع - Crossref', url: 'https://search.crossref.org', type: 'platform' },
    ],
  },
  {
    id: 'uni-cs-ai-engineering',
    titleAr: 'علوم الحاسوب والذكاء الاصطناعي والهندسة',
    titleEn: 'Computer Science, AI & Engineering',
    icon: 'Terminal',
    stage: 'university',
    descriptionAr: 'خوارزميات وهياكل البيانات، تعلم الآلة، هندسة البرمجيات، الأنظمة الموزعة، وهندسة المتحكمات وشبكات الاتصال.',
    descriptionEn: 'Algorithms & Data Structures, Machine Learning, Distributed Systems, Software Architecture, and Embedded Systems.',
    topics: [
      {
        titleAr: 'تعقيد الخوارزميات وتحليل الأداء (Big-O Notation)',
        titleEn: 'Algorithmic Complexity & Big-O Notation',
        summaryAr: 'تحليل الزمن والمساحة (Time & Space Complexity) لأشهر خوارزميات الترتيب والبحث: O(1), O(log n), O(n), O(n log n), O(n²).',
        summaryEn: 'Time and space complexity for sorting, searching, and dynamic programming algorithms.',
        keyPointsAr: ['O(1): زمن ثابت ومستقل عن حجم المدخلات', 'O(log n): شجري وثنائي كالبحث الثنائي (Binary Search)', 'الترتيب السريع والدمج: O(n log n)'],
        keyPointsEn: ['O(1) constant time', 'O(log n) binary tree operations', 'Quicksort & Mergesort average O(n log n)'],
        practicePrompt: 'اشرح بالتفصيل كيف يعمل خوارزمية البحث الثنائي (Binary Search) مع رسم بياني وشيفرة بايثون وحساب تعقيدها.',
      },
    ],
    referenceLinks: [
      { title: 'محاضرات علوم الحاسوب من MIT - MIT OCW CS', url: 'https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/', type: 'courses' },
      { title: 'مستودع أبحاث الذكاء الاصطناعي - arXiv CS.AI', url: 'https://arxiv.org/list/cs.AI/recent', type: 'preprints' },
    ],
  },
];
